import type { GData } from "./adventureland-data"

/**
 * The following is from http://adventure.land/data.js, version 5140 (2026-08-25)
 * It is used to confirm type correctness
 */

test("G.sets type validation", async () => {
    const G_sets: Pick<GData, "sets"> = {
        sets: {
            bunny: {
                "1": {},
                "2": { luck: 5 },
                "3": { vit: 3 },
                "4": { speed: 2 },
                "5": { cuteness: 50, vit: 2 },
                "6": { vit: 2 },
                explanation: "An Easter / Bunny themed set!",
                items: ["eears", "ecape", "epyjamas", "eslippers", "pinkie", "carrotsword"],
                name: "Bunny Set",
            },
            fury: {
                "1": {},
                "2": { str: 1 },
                "3": { dex: 2 },
                "4": { apiercing: 32 },
                items: ["suckerpunch", "suckerpunch", "fury", "fallen"],
                name: "Rage and Fury",
            },
            holidays: {
                "1": {},
                "2": { dex: 1 },
                "3": { vit: 1 },
                "4": { luck: 6 },
                "5": {},
                "6": {},
                "7": {},
                explanation: "Every month is December with this set!",
                items: [
                    "xmashat",
                    "xmassweater",
                    "xmasshoes",
                    "xmaspants",
                    "mittens",
                    "supermittens",
                    "santasbelt",
                    "ornamentstaff",
                    "candycanesword",
                    "merry",
                    "orbofsc",
                    "mearring",
                    "xmace",
                    "ringhs",
                    "sweaterhs",
                    "wbookhs",
                    "orboftemporal",
                ],
                name: "Holiday Spirit",
            },
            legends: {
                "1": {},
                "2": {},
                "3": { for: 10 },
                "4": { for: 2 },
                items: ["warpvest", "starkillers", "powerglove", "goldenpowerglove"],
                name: "The Legends",
            },
            mmage: {
                "1": {},
                "2": { int: 2 },
                "3": { int: 3, speed: 2 },
                "4": { rpiercing: 40 },
                "5": { crit: 2, phresistance: 25, stresistance: 20 },
                explanation: "A set for a noble mage who serves our realm!",
                items: ["mmhat", "mmarmor", "mmgloves", "mmpants", "mmshoes"],
                name: "Monster Hunter Mage",
            },
            mmerchant: {
                "1": {},
                "2": { courage: 1, mcourage: 1, pcourage: 1, vit: 6 },
                "3": { speed: 2, str: 3, vit: 8 },
                "4": { evasion: 6 },
                "5": { courage: 2, for: 32, mcourage: 2, pcourage: 2, phresistance: 25, stresistance: 20 },
                explanation: "A set for a noble merchant who has some friends that serve our realm!",
                items: ["mchat", "mcarmor", "mcgloves", "mcpants", "mcboots"],
                name: "Monster Hunter Merchant",
            },
            mpriest: {
                "1": {},
                "2": { int: 3 },
                "3": { int: 3, speed: 2 },
                "4": { rpiercing: 120 },
                "5": { mp: 2000, phresistance: 25, stresistance: 20 },
                explanation: "A set for a noble priest who serves our realm!",
                items: ["mphat", "mparmor", "mpgloves", "mppants", "mpshoes"],
                name: "Monster Hunter Priest",
            },
            mpx: {
                "1": {},
                "2": { mp: 100 },
                "3": { mp: 500, rpiercing: 20, speed: 1 },
                items: ["mpxbelt", "mpxgloves", "mpxamulet"],
                name: "MP X",
            },
            mranger: {
                "1": {},
                "2": { dex: 3 },
                "3": { dex: 3, speed: 2 },
                "4": { apiercing: 60 },
                "5": { phresistance: 25, resistance: 100, stresistance: 20 },
                explanation: "A set for a noble ranger who serves our realm!",
                items: ["mrnhat", "mrnarmor", "mrngloves", "mrnpants", "mrnboots"],
                name: "Monster Hunter Ranger",
            },
            mrogue: {
                "1": {},
                "2": { dex: 6 },
                "3": { dex: 4, speed: 3 },
                "4": { apiercing: 80 },
                "5": { crit: 5, phresistance: 25, stresistance: 20 },
                explanation: "A set for a noble rogue who serves our realm!",
                items: ["mrhood", "mrarmor", "mrgloves", "mrpants", "mrboots"],
                name: "Monster Hunter Rogue",
            },
            mwarrior: {
                "1": {},
                "2": { str: 2 },
                "3": { speed: 1, str: 3 },
                "4": { apiercing: 40 },
                "5": { crit: 5, phresistance: 25, stresistance: 20 },
                explanation: "A set for a noble warrior who serves our realm!",
                items: ["mwhelmet", "mwarmor", "mwgloves", "mwpants", "mwboots"],
                name: "Monster Hunter Warrior",
            },
            rugged: {
                "1": {},
                "2": { dex: 1, int: 1, str: 1 },
                "3": { armor: 20, range: 2, resistance: 20 },
                "4": { for: 8 },
                "5": { phresistance: 25, speed: 4, stresistance: 20 },
                explanation: "Just the right amount of protection for the agile wearer",
                items: ["helmet1", "coat1", "shoes1", "gloves1", "pants1"],
                name: "Rugged Set",
            },
            swift: { "1": {}, "2": { dex: 1 }, items: ["wingedboots", "fierygloves"], name: "Swift Judgement" },
            tiger: {
                "1": {},
                "2": { vit: 1 },
                "3": { dex: 5, int: 5, str: 5 },
                "4": { speed: 3 },
                items: ["tigerhelmet", "tigershield", "tigercape", "tigerstone"],
                name: "Tigers'",
            },
            vampires: {
                "1": {},
                "2": { vit: 10 },
                "3": { lifesteal: 1 },
                items: [
                    "mcape",
                    "vgloves",
                    "vboots",
                    "vattire",
                    "vcape",
                    "vorb",
                    "vhammer",
                    "vdagger",
                    "vstaff",
                    "vsword",
                    "vblood",
                    "vring",
                ],
                name: "Vampires",
            },
            wanderers: {
                "1": {},
                "2": { hp: 200 },
                "3": { mp: 100 },
                "4": { gold: 10 },
                "5": { luck: 16 },
                explanation:
                    "Wanderer was a curious adventurer. Traveling from place to place. The items he left over make up a very lucky set when they are combined.",
                items: ["wcap", "wattire", "wbreeches", "wgloves", "wshoes"],
                name: "Wanderer's Set",
            },
            wt3: {
                "1": { for: 2 },
                "2": { for: 4 },
                "3": { for: 6 },
                "4": { for: 10 },
                "5": { for: 16 },
                items: ["hhelmet", "harmor", "hboots", "hgloves", "hpants"],
                name: "Heavy Armor",
            },
            wt4: {
                "1": { for: 3 },
                "2": { for: 5 },
                "3": { for: 7 },
                "4": { for: 15 },
                "5": { for: 22 },
                items: ["xhelmet", "xarmor", "xboots", "xgloves", "xpants"],
                name: "Darkforge Armor",
            },
        },
    }
    expect(G_sets).toBeDefined()
})
