import type { GData } from "./adventureland-data"

/**
 * The following is from http://adventure.land/data.js, version 5140 (2026-08-25)
 * It is used to confirm type correctness
 */

test("G.classes type validation", async () => {
    const G_classes: Pick<GData, "classes"> = {
        classes: {
            mage: {
                armor: 2,
                attack: 30,
                base_slots: { mainhand: { gift: 1, level: 0, name: "staff" } },
                courage: 2,
                damage_type: "magical",
                description:
                    "Mage's are the ideal characters for beginners. They are easy and fun to play. Both PVE and PVP.",
                doublehand: { great_staff: { frequency: -10, mp_cost: 160, speed: -12 } },
                frequency: 0.35,
                hp: 70,
                looks: [
                    ["marmor12d", { head: "makeup117" }],
                    ["mbody5f", { head: "fmakeup01" }],
                    ["marmor12d", { head: "makeup105" }],
                    ["mbody5f", { head: "fmakeup03" }],
                ],
                lstats: { dex: 0.2, for: 0.02, int: 1, str: 0.2, vit: 0.3 },
                main_stat: "int",
                mainhand: { staff: { speed: -4 }, wand: { frequency: 60, mp_cost: -18 }, wblade: { speed: -5 } },
                mcourage: 3,
                mp: 300,
                mp_cost: 5,
                offhand: { misc_offhand: { speed: -4 }, source: {} },
                output: 100,
                pcourage: 2,
                projectile: "magic",
                range: 120,
                resistance: 5,
                speed: 45,
                stats: { dex: 3, for: 2, int: 10, str: 2, vit: 3 },
                xcx: ["marmor12f", "mbody5h", "hairdo402"],
            },
            merchant: {
                armor: 20,
                attack: 10,
                base_slots: { mainhand: { gift: 1, level: 0, name: "staff" } },
                courage: 1,
                damage_type: "none",
                description:
                    "While your main characters are out there adventuring, merchants can wait in town and market your loots. Server and character limits don't apply to merchants. They gain experience when they sell or buy something.",
                doublehand: {
                    axe: { speed: -20 },
                    basher: { speed: -26 },
                    pickaxe: { speed: -20 },
                    rod: { speed: -20 },
                },
                frequency: 0.05,
                hp: 40,
                looks: [
                    ["marmor12a", { hair: "hairdo521", hat: "hat404", head: "makeup117" }],
                    ["marmor12b", { hair: "hairdo520", head: "fmakeup01" }],
                    ["marmor12a", { hair: "hairdo521", hat: "hat404", head: "makeup105" }],
                    ["marmor12b", { hair: "hairdo520", head: "fmakeup03" }],
                ],
                lstats: { dex: 0.4, for: 0, int: 1, str: 0.1, vit: 0.25 },
                main_stat: "int",
                mainhand: {
                    bow: { speed: -6 },
                    dagger: { speed: -3 },
                    dartgun: {},
                    fist: { speed: -2 },
                    mace: { speed: -10 },
                    short_sword: { speed: -5 },
                    spear: { speed: -5 },
                    staff: { speed: -4 },
                },
                mcourage: 0,
                mp: 200,
                mp_cost: 10,
                offhand: { misc_offhand: { speed: -3 }, quiver: { speed: -2 }, shield: { speed: -8 }, source: {} },
                output: 10,
                pcourage: 0,
                projectile: "momentum",
                range: 20,
                resistance: 20,
                speed: 55,
                stats: { dex: 4, for: 0, int: 12, str: 1, vit: 1 },
            },
            paladin: {
                armor: 20,
                attack: 60,
                base_slots: { mainhand: { gift: 1, level: 0, name: "mace" } },
                bmresistance: 10,
                courage: 2,
                damage_type: "physical",
                description: "Paladins are an unbalanced mix-use class!",
                doublehand: {},
                frequency: 0.4,
                hp: 300,
                looks: [
                    ["marmor4b", { hair: "hairdo515", head: "makeup117" }],
                    ["marmor4b", { hair: "hairdo405", head: "fmakeup01" }],
                    ["marmor4b", { hair: "hairdo515", head: "makeup105" }],
                    ["marmor4b", { hair: "hairdo405", head: "fmakeup03" }],
                ],
                lstats: { dex: 0.05, for: 0.2, int: 1, str: 1, vit: 0.4 },
                main_stat: "str",
                mainhand: {
                    mace: {},
                    short_sword: { output: -5, speed: -3 },
                    sword: { frequency: -5, output: -5, speed: -7 },
                },
                mcourage: 4,
                mp: 50,
                mp_cost: 2,
                offhand: { misc_offhand: {}, shield: { speed: -3 }, source: {} },
                output: 100,
                pcourage: 5,
                projectile: "momentum",
                range: 15,
                resistance: 2,
                side_stat: "int",
                speed: 45,
                stats: { dex: 2, for: 5, int: 10, str: 10, vit: 4 },
                stresistance: 10,
            },
            priest: {
                armor: 2,
                attack: 30,
                base_slots: { mainhand: { gift: 1, level: 0, name: "staff" } },
                courage: 2,
                damage_type: "magical",
                description:
                    "Priest's are the healers of the realm. They are not ideal for beginners or solo players. They can't inflict a lot of damage. Every serious party needs at least one priest.",
                doublehand: { wand: { frequency: 40 } },
                frequency: 0.35,
                hp: 70,
                looks: [
                    ["marmor12c", { head: "makeup117" }],
                    ["mbody5e", { head: "fmakeup01" }],
                    ["marmor12c", { head: "makeup105" }],
                    ["mbody5e", { head: "fmakeup03" }],
                ],
                lstats: { dex: 0.2, for: 0.025, int: 1, str: 0.2, vit: 0.4 },
                main_stat: "int",
                mainhand: { pmace: { speed: -2 }, staff: { speed: -4 } },
                mcourage: 5,
                mp: 300,
                mp_cost: 5,
                offhand: { misc_offhand: { speed: -4 }, shield: { speed: -5 }, source: {} },
                output: 40,
                pcourage: 2,
                projectile: "pmagic",
                range: 120,
                resistance: 5,
                speed: 45,
                stats: { dex: 3, for: 3, int: 10, str: 2, vit: 4 },
                xcx: ["marmor12e", "mbody5g", "hairdo402"],
            },
            ranger: {
                armor: 10,
                attack: 45,
                base_slots: { mainhand: { gift: 1, level: 0, name: "bow" } },
                courage: 2,
                damage_type: "physical",
                description:
                    "Rangers are skilled archers. Expert trackers. Their high range makes them very suitable for beginners.",
                doublehand: { dagger: {}, fist: {} },
                frequency: 0.4,
                hp: 160,
                looks: [
                    ["marmor5a", { hair: "hairdo106", head: "makeup117" }],
                    ["mbody2b", { hair: "hairdo206", head: "fmakeup01", makeup: "facemakeup02" }],
                    ["marmor5a", { hair: "hairdo106", head: "makeup105" }],
                    ["mbody2b", { hair: "hairdo206", head: "fmakeup03", makeup: "facemakeup02" }],
                ],
                lstats: { dex: 1, for: 0.02, int: 0.25, str: 0.2, vit: 0.3 },
                main_stat: "dex",
                mainhand: { bow: { speed: -3 }, crossbow: { apiercing: 120, frequency: -36 } },
                mcourage: 2,
                mp: 60,
                mp_cost: 2,
                offhand: { quiver: {} },
                output: 100,
                pcourage: 2,
                pnresistance: 10,
                projectile: "momentum",
                range: 15,
                resistance: 80,
                speed: 45,
                stats: { dex: 10, for: 1, int: 8, str: 3, vit: 2 },
            },
            rogue: {
                armor: 15,
                attack: 45,
                base_slots: { mainhand: { gift: 1, level: 0, name: "claw" } },
                courage: 2,
                damage_type: "physical",
                description:
                    "Rogue's are the ideal assassins. Their invis ability makes them super-fun for PVP. They are fast. Not ideal for beginners.",
                doublehand: {
                    bow: { frequency: -30, miss: 30, speed: -10 },
                    rapier: { frequency: 70 },
                    short_sword: {},
                    spear: { frequency: 16, speed: -3 },
                },
                frequency: 0.45,
                fzresistance: 10,
                hp: 120,
                looks: [
                    ["sbody1c", { chin: "beard112", hair: "hairdo522", head: "makeup117" }],
                    ["sarmor1h", { hair: "hairdo210", head: "fmakeup01" }],
                    ["sbody1c", { chin: "beard112", hair: "hairdo522", head: "makeup105" }],
                    ["sarmor1h", { hair: "hairdo210", head: "fmakeup03" }],
                ],
                lstats: { dex: 1, for: 0.025, int: 0.2, str: 0.2, vit: 0.3 },
                main_stat: "dex",
                mainhand: { dagger: {}, fist: {}, stars: { frequency: 20 } },
                mcourage: 2,
                mp: 30,
                mp_cost: 1,
                offhand: { dagger: {}, fist: {}, misc_offhand: { speed: -4 }, stars: {} },
                output: 100,
                pcourage: 2,
                projectile: "momentum",
                range: 15,
                resistance: 10,
                speed: 50,
                stats: { dex: 10, for: 2, int: 3, str: 4, vit: 3 },
            },
            warrior: {
                armor: 20,
                attack: 60,
                base_slots: { mainhand: { gift: 1, level: 0, name: "blade" } },
                brave: true,
                courage: 5,
                damage_type: "physical",
                description:
                    "Warriors are strong melee characters. Ideal for both PVE and PVP. Can't go wrong with a warrior.",
                doublehand: {
                    axe: { frequency: -10, mp_cost: 6, speed: -7 },
                    basher: { frequency: -12, mp_cost: 12, speed: -12 },
                    bow: { frequency: -40, miss: 50, speed: -12 },
                    great_sword: { frequency: -8, mp_cost: 6, speed: -5 },
                    rapier: { frequency: 60, miss: 2, mp_cost: 4 },
                    scythe: { frequency: -11, mp_cost: 8, speed: -6 },
                },
                frequency: 0.5,
                hp: 200,
                looks: [
                    ["marmor6d", { hair: "hairdo105", head: "makeup117" }],
                    ["sarmor2d", { hair: "hairdo120", head: "fmakeup01" }],
                    ["marmor6d", { hair: "hairdo105", head: "makeup105" }],
                    ["sarmor2d", { hair: "hairdo120", head: "fmakeup03" }],
                ],
                lstats: { dex: 0.25, for: 0.025, int: 0.25, str: 1, vit: 0.4 },
                main_stat: "str",
                mainhand: {
                    fist: { frequency: 6 },
                    mace: { frequency: -8, speed: -4 },
                    short_sword: {},
                    spear: { speed: -2 },
                    sword: { speed: -5 },
                },
                mcourage: 2,
                mp: 20,
                mp_cost: 1,
                offhand: {
                    fist: { frequency: 6 },
                    mace: { frequency: -6, speed: -5 },
                    misc_offhand: { frequency: -12, speed: -8 },
                    shield: { speed: -2 },
                    short_sword: { speed: -5 },
                    sword: { speed: -5 },
                },
                output: 100,
                pcourage: 2,
                phresistance: 10,
                projectile: "momentum",
                range: 18,
                resistance: 2,
                speed: 55,
                stats: { dex: 2, for: 2, int: 2, str: 10, vit: 4 },
                xcx: [],
            },
        },
    }
    expect(G_classes).toBeDefined()
})
