import type { GData } from "./adventureland-data"

/**
 * The following is from http://adventure.land/data.js, version 8535 (2026-09-07)
 * It is used to confirm type correctness
 */

test("G.sprites type validation", async () => {
    const G_sprites: Pick<GData, "sprites"> = {
        sprites: {
            adversaries: {
                columns: 4,
                file: "/images/tiles/characters/adversaries.png",
                matrix: [
                    ["a1", "a2", "a3", "a4"],
                    ["a5", "a6", "a7", "a8"],
                ],
                rows: 2,
            },
            angel_wingless: {
                columns: 4,
                file: "/images/tiles/characters/angel_wingless.png",
                matrix: [
                    [null, "bangel", null, null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            animals1: {
                columns: 4,
                file: "/images/tiles/monsters/animals1.png",
                matrix: [
                    ["puppy1", "puppy2", "puppy3", "puppy4"],
                    ["kitty1", "kitty2", "kitty3", "kitty4"],
                ],
                rows: 2,
            },
            animals2: {
                columns: 4,
                file: "/images/tiles/monsters/animals2.png",
                matrix: [
                    [null, null, null, null],
                    ["porcupine", null, null, null],
                ],
                rows: 2,
            },
            animation1: {
                columns: 4,
                file: "/images/tiles/characters/animation1i.png",
                matrix: [
                    [null, "pflow", "sidesword", "flute"],
                    [null, "fancypots", "pike", "doublesword"],
                    [null, null, "daggers", "hammer"],
                    [null, null, "swdagger", "miniharp"],
                    ["bow", "spell", "powerup", "magic"],
                    ["bow2", "sth1", "tricks", "yellowlady"],
                    ["praise", "drunk", "hairs", "yellowwarrior"],
                    ["femalesword", "femalelongsword", "scrolls", "double-axe"],
                ],
                rows: 8,
                type: "animation",
            },
            animation2: {
                columns: 4,
                file: "/images/tiles/characters/animation2.png",
                matrix: [
                    ["armorguy", "zengirl", null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                    [null, "goblin_a", null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                ],
                rows: 8,
                type: "animation",
            },
            animation3: {
                columns: 4,
                file: "/images/tiles/characters/animation3.png",
                matrix: [
                    [null, null, null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                    ["geekgirl", null, null, null],
                    [null, null, null, null],
                    [null, "exchanger", null, null],
                    [null, null, null, null],
                    [null, "newupgrade", null, null],
                ],
                rows: 8,
                type: "animation",
            },
            animationc: {
                columns: 4,
                file: "/images/tiles/characters/animationc.png?v=4",
                matrix: [
                    ["santa", "pvptokens", null, null],
                    ["brewingwitch", "funtokens", null, null],
                    ["test_a", null, "test_b", null],
                    [null, null, null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                    [null, null, null, null],
                ],
                rows: 8,
                type: "animation",
            },
            aniv2: {
                columns: 1,
                file: "/images/cosmetics/hats/aniv2_anim.png?v=1",
                frames: 6,
                matrix: [["aniv2"]],
                rows: 1,
                type: "a_hat",
            },
            automatron: {
                columns: 4,
                file: "/images/tiles/characters/automatron2.png",
                matrix: [
                    ["target_a500", "target_a750", "target_r500", "target_r750"],
                    ["target_ar900", "target_ar500red", null, "target"],
                ],
                rows: 2,
            },
            backpacks: {
                columns: 5,
                file: "/images/cosmetics/wings/backpacks.png",
                matrix: [["backpacks00", "backpacks01", "backpacks02", "backpacks03", "backpacks04"]],
                rows: 1,
                type: "s_wings",
            },
            backpacks2: {
                columns: 5,
                file: "/images/cosmetics/wings/backpack2.png",
                matrix: [["backpacks200", "backpacks201", null, null, null]],
                rows: 1,
                type: "s_wings",
            },
            bathat: {
                columns: 1,
                file: "/images/cosmetics/hats/bathat_anim.png",
                matrix: [["bathat"]],
                rows: 1,
                type: "a_hat",
            },
            beard1: {
                columns: 41,
                file: "/images/cosmetics/beardo/beard1.png?v=3",
                matrix: [
                    [
                        "beard100",
                        "beard101",
                        "beard102",
                        "beard103",
                        "beard104",
                        "beard105",
                        "beard106",
                        "beard107",
                        "beard108",
                        "beard109",
                        "beard110",
                        "beard111",
                        "beard112",
                        "beard113",
                        "beard114",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "beard",
            },
            birds1: {
                columns: 4,
                file: "/images/tiles/monsters/birds1_modded.png",
                matrix: [
                    ["hen", "rooster", null, null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            boar: { columns: 1, file: "/images/tiles/monsters/monster_boar.png", matrix: [["boar"]], rows: 1 },
            bonus1: {
                columns: 4,
                file: "/images/tiles/characters/bonus1.png",
                matrix: [
                    [null, null, null, null],
                    [null, null, "mranger", "holo"],
                ],
                rows: 2,
            },
            bscorpion: {
                columns: 1,
                file: "/images/tiles/monsters/blackscorpion.png",
                matrix: [["bscorpion"]],
                rows: 1,
            },
            burningeyes1: {
                columns: 1,
                file: "/images/cosmetics/beardo/burningeyes1_anim.png",
                matrix: [["breyes"]],
                rows: 1,
                type: "a_makeup",
            },
            burningeyes2: {
                columns: 1,
                file: "/images/cosmetics/beardo/burningeyes2_anim.png",
                matrix: [["bbeyes"]],
                rows: 1,
                type: "a_makeup",
            },
            bwhair: {
                columns: 1,
                file: "/images/cosmetics/hairdo/bwhair.png?v=2",
                matrix: [["bwhair"]],
                rows: 1,
                type: "hair",
            },
            cacto: {
                columns: 1,
                file: "/images/tiles/monsters/monster_cacto.png",
                matrix: [["cactusman"]],
                rows: 1,
                skip: 1,
            },
            cbee: { columns: 1, file: "/images/tiles/monsters/cbee.png", matrix: [["cutebee"]], rows: 1 },
            chara2: {
                columns: 4,
                file: "/images/tiles/characters/chara2.png",
                matrix: [
                    [null, null, "thief", "fxrogue"],
                    [null, null, "generalg", "prince"],
                ],
                rows: 2,
            },
            chara3: {
                columns: 4,
                file: "/images/tiles/characters/chara3.png",
                matrix: [
                    [null, null, "franger", "lilith"],
                    [null, null, "frogue", null],
                ],
                rows: 2,
            },
            chara4: {
                columns: 4,
                file: "/images/tiles/characters/chara4.png",
                matrix: [
                    [null, "ftokener", "grogue", null],
                    ["shadow", "angel", null, null],
                ],
                rows: 2,
            },
            chara5: {
                columns: 4,
                file: "/images/tiles/characters/chara5.png",
                matrix: [
                    [null, null, null, "thehelmet"],
                    [null, "mpriest", "reaper", "goblin"],
                ],
                rows: 2,
            },
            chara6: {
                columns: 4,
                file: "/images/tiles/characters/chara6.png",
                matrix: [
                    ["mwarrior", "mnwarrior", "mwarrior_cool", "fpaladin"],
                    ["fkid", "redhead", "mrogue", "mpaladin_kid"],
                ],
                rows: 2,
            },
            chara7: {
                columns: 4,
                file: "/images/tiles/characters/chara7.png",
                matrix: [
                    ["frozenrogue", null, "fmage", null],
                    ["marven", "fwarrior", "blingbling", "lionsuit"],
                ],
                rows: 2,
            },
            chara8: {
                columns: 4,
                file: "/images/tiles/characters/chara8.png",
                matrix: [
                    ["pink", "splithair", "wizard", "pwincess"],
                    ["greencap", null, null, null],
                ],
                rows: 2,
            },
            chests: {
                columns: 12,
                file: "/images/tiles/items/chests.png?v=2",
                matrix: [
                    ["chestp", "chest1", null, null, "chest2", null, null, "chest3", null, null, "chest4", null],
                    [null, "chest5", null, null, "chest6", null, null, "chest7", null, null, "chest8", null],
                ],
                rows: 2,
                type: "v_animation",
            },
            cobold: { columns: 1, file: "/images/tiles/monsters/coboldProto.png", matrix: [["cobold"]], rows: 1 },
            collection1: {
                columns: 4,
                file: "/images/tiles/characters/collection1.png",
                matrix: [
                    ["daisy", null, null, null],
                    [null, null, "cunn", "robbie"],
                ],
                rows: 2,
            },
            collection2: {
                columns: 4,
                file: "/images/tiles/characters/collection2.png",
                matrix: [
                    ["sir", null, null, null],
                    [null, null, "naked", null],
                ],
                rows: 2,
            },
            collectionx: {
                columns: 4,
                file: "/images/tiles/characters/collectionx.png",
                matrix: [
                    [null, "snow_angel", null, null],
                    ["creator", null, null, null],
                ],
                rows: 2,
            },
            creatures1: {
                columns: 4,
                file: "/images/tiles/monsters/creatures1.png",
                matrix: [[null, null, "mummy", "booboo"]],
                rows: 1,
            },
            creatures2: {
                columns: 4,
                file: "/images/tiles/monsters/creatures2.png",
                matrix: [
                    ["oneeye", null, null, null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            custom1: {
                columns: 4,
                file: "/images/tiles/characters/custom1.png?v=11",
                matrix: [
                    ["mwarrior2", "mranger2", "fpriest", "trexw"],
                    ["showoffi", "bpri", "mmage", "enterrr"],
                ],
                rows: 2,
            },
            custom2: {
                columns: 4,
                file: "/images/tiles/characters/custom2.png?v=4",
                matrix: [
                    ["trexp", null, null, null],
                    ["konami", "potiongirl", "j2", null],
                ],
                rows: 2,
            },
            custom3: {
                columns: 4,
                file: "/images/tiles/characters/custom3.png?v=1",
                matrix: [
                    ["spkc", "spkw", "bunny", "bouncer"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            deepsea: { columns: 1, file: "/images/tiles/monsters/deep_sea_king.png", matrix: [["deepsea"]], rows: 1 },
            dinos: {
                columns: 4,
                file: "/images/tiles/monsters/mondinos_1.png",
                matrix: [
                    [null, null, null, null],
                    ["gdino", "odino", "bdino", "wdino"],
                ],
                rows: 2,
            },
            dknight1: {
                columns: 1,
                file: "/images/tiles/monsters/monster_dknight1.png",
                matrix: [["dknight1"]],
                rows: 1,
                skip: 1,
            },
            dknight2: {
                columns: 1,
                file: "/images/tiles/monsters/monster_dknight2.png",
                matrix: [["dknight2"]],
                rows: 1,
            },
            dragold: { columns: 1, file: "/images/tiles/monsters/Dragold.png?v=2", matrix: [["dragold"]], rows: 1 },
            dryad: { columns: 1, file: "/images/tiles/monsters/dryad_green_1.png", matrix: [["dryad"]], rows: 1 },
            dwarf2: {
                columns: 4,
                file: "/images/tiles/characters/dwarf2.png",
                matrix: [
                    [null, null, null, null],
                    ["fancyd", null, null, null],
                ],
                rows: 2,
            },
            elementals: {
                columns: 4,
                file: "/images/tiles/monsters/elemental.png",
                matrix: [
                    ["welemental", "felemental", "nelemental", "eelemental"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            elk: { columns: 1, file: "/images/tiles/monsters/monster_elk.png", matrix: [["elk"]], rows: 1, skip: 1 },
            emblems: {
                columns: 10,
                file: "/images/sprites/emblems/emblems.png?v=6",
                matrix: [
                    ["c1", "c2", "c3", "c4", "b1", "r1", "rr1", "dp1", null, null],
                    ["m1", "m2", "m3", "m4", "b2", "br1", "o1", "j1", null, null],
                ],
                rows: 2,
                type: "emblem",
            },
            face1: {
                columns: 41,
                file: "/images/cosmetics/accessories/eyeglasses.png?v=3",
                matrix: [
                    [
                        "face100",
                        "face101",
                        "face102",
                        "face103",
                        "face104",
                        "face105",
                        "face106",
                        "face107",
                        "face108",
                        "face109",
                        "face110",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "face",
            },
            facemakeup: {
                columns: 25,
                file: "/images/cosmetics/beardo/facemakeup.png?v=2",
                matrix: [
                    [
                        "facemakeup00",
                        "facemakeup01",
                        "facemakeup02",
                        "facemakeup03",
                        "facemakeup04",
                        "facemakeup05",
                        "facemakeup06",
                        "facemakeup07",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "makeup",
            },
            fairies: {
                columns: 4,
                file: "/images/tiles/monsters/fairies.png",
                matrix: [
                    ["greenfairy", "redfairy", "bluefairy", "darkfairy"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            fmakeup: {
                columns: 13,
                file: "/images/cosmetics/makeup/femalemakeupv2.png",
                matrix: [
                    [
                        "fmakeup00",
                        "fmakeup01",
                        "fmakeup02",
                        "fmakeup03",
                        "fmakeup04",
                        "fmakeup05",
                        "fmakeup06",
                        "fmakeup07",
                        "fmakeup08",
                        "fmakeup09",
                        "fmakeup10",
                        "fmakeup11",
                        "fmakeup12",
                    ],
                ],
                rows: 1,
                type: "head",
            },
            franky: { columns: 1, file: "/images/tiles/monsters/frankenstein.png", matrix: [["franky"]], rows: 1 },
            gcandle: {
                columns: 1,
                file: "/images/cosmetics/hats/gcandle_anim.png",
                matrix: [["gcandle"]],
                rows: 1,
                type: "a_hat",
            },
            gking: { columns: 1, file: "/images/tiles/monsters/goblinkingb.png", matrix: [["gking"]], rows: 1 },
            goblinos: {
                columns: 4,
                file: "/images/tiles/monsters/goblinos.png",
                matrix: [
                    [null, null, "gredpro", "ggreenpro"],
                    [null, null, "gpurplepro", "gbluepro"],
                ],
                rows: 2,
            },
            golem1: {
                columns: 1,
                file: "/images/tiles/monsters/monster_golem1.png",
                matrix: [["stone_golem"]],
                rows: 1,
                skip: 1,
            },
            golem2: {
                columns: 1,
                file: "/images/tiles/monsters/monster_golem2.png",
                matrix: [["tree_golem"]],
                rows: 1,
                skip: 1,
            },
            goos: {
                columns: 5,
                file: "/images/tiles/monsters/goos.png",
                matrix: [
                    ["goo0", "goo1", "goo2", "goo3", "goo4"],
                    ["goo5", "goo6", "goo7", "goo8", "gooD"],
                ],
                rows: 2,
            },
            gravestones: {
                columns: 10,
                file: "/images/cosmetics/gravestones/gravestone.png",
                matrix: [
                    [
                        "gravestonea",
                        "gravestone",
                        "xgravestone0",
                        "xgravestone1",
                        "xgravestone2",
                        "xgravestone3",
                        "xgravestone4",
                        null,
                        null,
                        null,
                    ],
                    [null, null, null, null, null, null, null, null, null, null],
                ],
                rows: 2,
                rskip: true,
                type: "gravestone",
            },
            grinch: { columns: 1, file: "/images/tiles/monsters/grinch.png", matrix: [["grinch"]], rows: 1 },
            hairdo1: {
                columns: 25,
                file: "/images/cosmetics/hairdo/hairdo1.png?v=7",
                matrix: [
                    [
                        "hairdo100",
                        "hairdo101",
                        "hairdo102",
                        "hairdo103",
                        "hairdo104",
                        "hairdo105",
                        "hairdo106",
                        "hairdo107",
                        "hairdo108",
                        "hairdo109",
                        "hairdo110",
                        "hairdo111",
                        "hairdo112",
                        "hairdo113",
                        "hairdo114",
                        "hairdo115",
                        "hairdo116",
                        "hairdo117",
                        "hairdo118",
                        "hairdo119",
                        "hairdo120",
                        "hairdo121",
                        "hairdo122",
                        "hairdo123",
                        "hairdo124",
                    ],
                ],
                rows: 1,
                type: "hair",
            },
            hairdo2: {
                columns: 25,
                file: "/images/cosmetics/hairdo/hairdo2.png?v=7",
                matrix: [
                    [
                        "hairdo200",
                        "hairdo201",
                        "hairdo202",
                        "hairdo203",
                        "hairdo204",
                        "hairdo205",
                        "hairdo206",
                        "hairdo207",
                        "hairdo208",
                        "hairdo209",
                        "hairdo210",
                        "hairdo211",
                        "hairdo212",
                        "hairdo213",
                        "hairdo214",
                        "hairdo215",
                        "hairdo216",
                        "hairdo217",
                        "hairdo218",
                        "hairdo219",
                        "hairdo220",
                        "hairdo221",
                        "hairdo222",
                        "hairdo223",
                        "hairdo224",
                    ],
                ],
                rows: 1,
                type: "hair",
            },
            hairdo3: {
                columns: 25,
                file: "/images/cosmetics/hairdo/hairdo3.png?v=7",
                matrix: [
                    [
                        "hairdo300",
                        "hairdo301",
                        "hairdo302",
                        "hairdo303",
                        "hairdo304",
                        "hairdo305",
                        "hairdo306",
                        "hairdo307",
                        "hairdo308",
                        "hairdo309",
                        "hairdo310",
                        "hairdo311",
                        "hairdo312",
                        "hairdo313",
                        "hairdo314",
                        "hairdo315",
                        "hairdo316",
                        "hairdo317",
                        "hairdo318",
                        "hairdo319",
                        "hairdo320",
                        "hairdo321",
                        "hairdo322",
                        "hairdo323",
                        "hairdo324",
                    ],
                ],
                rows: 1,
                type: "hair",
            },
            hairdo4: {
                columns: 25,
                file: "/images/cosmetics/hairdo/hairdo4.png?v=7",
                matrix: [
                    [
                        "hairdo400",
                        "hairdo401",
                        "hairdo402",
                        "hairdo403",
                        "hairdo404",
                        "hairdo405",
                        "hairdo406",
                        "hairdo407",
                        "hairdo408",
                        "hairdo409",
                        "hairdo410",
                        "hairdo411",
                        "hairdo412",
                        "hairdo413",
                        "hairdo414",
                        "hairdo415",
                        "hairdo416",
                        "hairdo417",
                        "hairdo418",
                        "hairdo419",
                        "hairdo420",
                        "hairdo421",
                        "hairdo422",
                        "hairdo423",
                        "hairdo424",
                    ],
                ],
                rows: 1,
                type: "hair",
            },
            hairdo5: {
                columns: 25,
                file: "/images/cosmetics/hairdo/hairdo5.png?v=7",
                matrix: [
                    [
                        "hairdo500",
                        "hairdo501",
                        "hairdo502",
                        "hairdo503",
                        "hairdo504",
                        "hairdo505",
                        "hairdo506",
                        "hairdo507",
                        "hairdo508",
                        "hairdo509",
                        "hairdo510",
                        "hairdo511",
                        "hairdo512",
                        "hairdo513",
                        "hairdo514",
                        "hairdo515",
                        "hairdo516",
                        "hairdo517",
                        "hairdo518",
                        "hairdo519",
                        "hairdo520",
                        "hairdo521",
                        "hairdo522",
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "hair",
            },
            hairdo6: {
                columns: 25,
                file: "/images/cosmetics/hairdo/hairdo6.png?v=3",
                matrix: [
                    [
                        "hairdo600",
                        "hairdo601",
                        "hairdo602",
                        "hairdo603",
                        "hairdo604",
                        "hairdo605",
                        "hairdo606",
                        "hairdo607",
                        "hairdo608",
                        "hairdo609",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "hair",
            },
            halo: {
                columns: 1,
                file: "/images/cosmetics/hats/halo_anim.png",
                matrix: [["halo"]],
                rows: 1,
                type: "a_hat",
            },
            harpy: { columns: 1, file: "/images/tiles/monsters/harpy_b_1.png", matrix: [["harpy"]], rows: 1 },
            harpy_fly: {
                columns: 1,
                file: "/images/tiles/monsters/harpy_b_fly_1.png",
                matrix: [["harpy_fly"]],
                rows: 1,
            },
            hats1: {
                columns: 25,
                file: "/images/cosmetics/hats/hats1.png?v=2",
                matrix: [
                    [
                        "hat100",
                        "hat101",
                        "hat102",
                        "hat103",
                        "hat104",
                        "hat105",
                        "hat106",
                        "hat107",
                        "hat108",
                        "hat109",
                        "hat110",
                        "hat111",
                        "hat112",
                        "hat113",
                        "hat114",
                        "hat115",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "hat",
            },
            hats2: {
                columns: 25,
                file: "/images/cosmetics/hats/hats2.png?v=3",
                matrix: [
                    [
                        "hat200",
                        "hat201",
                        "hat202",
                        "hat203",
                        "hat204",
                        "hat205",
                        "hat206",
                        "hat207",
                        "hat208",
                        "hat209",
                        "hat210",
                        "hat211",
                        "hat212",
                        "hat213",
                        "hat214",
                        "hat215",
                        "hat216",
                        "hat217",
                        "hat218",
                        "hat219",
                        "hat220",
                        "hat221",
                        "hat222",
                        "hat223",
                        "hat224",
                    ],
                ],
                rows: 1,
                type: "hat",
            },
            hats3: {
                columns: 25,
                file: "/images/cosmetics/hats/hats3.png?v=2",
                matrix: [
                    [
                        "hat300",
                        "hat301",
                        "hat302",
                        "hat303",
                        "hat304",
                        "hat305",
                        "hat306",
                        "hat307",
                        "hat308",
                        "hat309",
                        "hat310",
                        "hat311",
                        "hat312",
                        "hat313",
                        "hat314",
                        "hat315",
                        "hat316",
                        "hat317",
                        "hat318",
                        "hat319",
                        "hat320",
                        "hat321",
                        "hat322",
                        "hat323",
                        null,
                    ],
                ],
                rows: 1,
                type: "hat",
            },
            hats4: {
                columns: 25,
                file: "/images/cosmetics/hats/hats4.png?v=5",
                matrix: [
                    [
                        "hat400",
                        "hat401",
                        "hat402",
                        "hat403",
                        "hat404",
                        "hat405",
                        "hat406",
                        "hat407",
                        "hat408",
                        "hat409",
                        "hat410",
                        "aniv0",
                        "aniv1",
                        "aniv3",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "hat",
            },
            icegolem: { columns: 1, file: "/images/tiles/monsters/iceGolem.png", matrix: [["icegolem"]], rows: 1 },
            jpa: {
                columns: 4,
                file: "/images/tiles/characters/winners_jpa.png",
                matrix: [
                    [null, "greengreen", null, "favore"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            jpb: {
                columns: 4,
                file: "/images/tiles/characters/winners_jpb.png",
                matrix: [
                    [null, "pinkie", null, "purpo"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            jrpumpkins: {
                columns: 2,
                file: "/images/tiles/monsters/jrpumpkins.png",
                matrix: [["jr", "greenjr"]],
                rows: 1,
            },
            json: { columns: 1, file: "/images/tiles/monsters/json.png", matrix: [["json"]], rows: 1 },
            jsonx: { columns: 1, file: "/images/tiles/characters/others/jsonX.png", matrix: [["jsonx"]], rows: 1 },
            jubchan: {
                columns: 1,
                file: "/images/tiles/characters/jubchan_1.png",
                height: 144,
                matrix: [["jubchan"]],
                rows: 1,
                width: 78,
            },
            kglasses: {
                columns: 4,
                file: "/images/cosmetics/accessories/kglasses.png?v=3",
                matrix: [["bwglasses", "tortoise_g", "catbatg", "coolblueg"]],
                rows: 1,
                type: "face",
            },
            knights: {
                columns: 4,
                file: "/images/tiles/characters/knights.png",
                matrix: [
                    ["pknight", null, "baron", null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            kunique: {
                columns: 4,
                file: "/images/cosmetics/makeup/kunique.png?v=2",
                matrix: [["bwhead", "blackhead", "testm1", "testm2"]],
                rows: 1,
                type: "head",
            },
            larmor1: {
                columns: 4,
                file: "/images/cosmetics/armors/larmor1.png",
                matrix: [
                    ["larmor1a", "larmor1b", null, null],
                    [null, null, null, null],
                ],
                rows: 2,
                size: "large",
                type: "armor",
            },
            lchar1: {
                columns: 4,
                file: "/images/all_characters/lchar1.png",
                matrix: [
                    ["lchar1a", "lchar1b", "lchar1c", "lchar1d"],
                    ["lchar1e", "lchar1f", "lchar1g", "lchar1h"],
                ],
                rows: 2,
                size: "large",
                type: "character",
            },
            ligerx: { columns: 1, file: "/images/tiles/monsters/liger_x.png", matrix: [["ligerx"]], rows: 1 },
            lizardman1: {
                columns: 1,
                file: "/images/tiles/monsters/monster_lizardman1.png",
                matrix: [["greenlizardman"]],
                rows: 1,
                skip: 1,
            },
            lizardman2: {
                columns: 1,
                file: "/images/tiles/monsters/monster_lizardman2.png",
                matrix: [["redlizardman"]],
                rows: 1,
                skip: 1,
            },
            lskin1: {
                columns: 4,
                file: "/images/cosmetics/skins/lskin1.png",
                matrix: [
                    ["lskin1a", "lskin1b", "lskin1c", "lskin1d"],
                    [null, null, null, null],
                ],
                rows: 2,
                size: "large",
                type: "skin",
            },
            mabw: {
                columns: 2,
                file: "/images/cosmetics/armors/mabw.png?v=2",
                matrix: [["mabw", "nothing"]],
                rows: 1,
                size: "normal",
                type: "armor",
            },
            mage: {
                columns: 4,
                file: "/images/tiles/monsters/mage.png",
                matrix: [
                    ["xmagefz", "xmagefi", "xmagen", "xmagex"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            makeup1: {
                columns: 42,
                file: "/images/cosmetics/makeup/makeup1.png?v=6",
                matrix: [
                    [
                        "makeup100",
                        "makeup101",
                        "makeup102",
                        "makeup103",
                        "makeup104",
                        "makeup105",
                        "makeup106",
                        "makeup107",
                        "makeup108",
                        "makeup109",
                        "makeup110",
                        "makeup111",
                        "makeup112",
                        "makeup113",
                        "makeup114",
                        "makeup115",
                        "makeup116",
                        "makeup117",
                        "makeup118",
                        "makeup119",
                        "makeup120",
                        "makeup121",
                        "makeup122",
                        "makeup123",
                        "makeup124",
                        "makeup125",
                        "makeup126",
                        "makeup127",
                        "makeup128",
                        "makeup129",
                        "makeup130",
                        "makeup131",
                        "makeup132",
                        "makeup133",
                        "makeup134",
                        "makeup135",
                        "makeup136",
                        "makeup137",
                        "makeup138",
                        "makeup139",
                        "makeup140",
                        "makeup141",
                    ],
                ],
                rows: 1,
                type: "head",
            },
            marmor1: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor1.png?v=2",
                matrix: [
                    ["marmor1a", "marmor1b", "marmor1c", "marmor1d"],
                    ["marmor1e", "marmor1f", "marmor1g", "marmor1h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor2: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor2.png?v=3",
                matrix: [
                    ["marmor2a", "marmor2b", "marmor2c", "marmor2d"],
                    ["marmor2e", "marmor2f", "marmor2g", "marmor2h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor3: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor3.png?v=2",
                matrix: [
                    ["marmor3a", "marmor3b", "marmor3c", "marmor3d"],
                    ["marmor3e", "marmor3f", "marmor3g", "marmor3h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor4: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor4.png?v=4",
                matrix: [
                    ["marmor4a", "marmor4b", "marmor4c", "marmor4d"],
                    ["marmor4e", "marmor4f", "marmor4g", "marmor4h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor5: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor5.png?v=4",
                matrix: [
                    ["marmor5a", "marmor5b", "marmor5c", "marmor5d"],
                    ["marmor5e", "marmor5f", "marmor5g", "marmor5h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor6: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor6.png?v=3",
                matrix: [
                    ["marmor6a", "marmor6b", "marmor6c", "marmor6d"],
                    ["marmor6e", "marmor6f", "marmor6g", "marmor6h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor7: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor7.png?v=2",
                matrix: [
                    ["marmor7a", "marmor7b", "marmor7c", "marmor7d"],
                    ["marmor7e", "marmor7f", "marmor7g", "marmor7h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor8: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor8.png?v=2",
                matrix: [
                    ["marmor8a", "marmor8b", "marmor8c", "marmor8d"],
                    ["marmor8e", "marmor8f", "marmor8g", "marmor8h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor9: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor9.png?v=2",
                matrix: [
                    ["marmor9a", "marmor9b", "marmor9c", "marmor9d"],
                    ["marmor9e", "marmor9f", "marmor9g", "marmor9h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor10: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor10.png",
                matrix: [
                    ["marmor10a", "marmor10b", "marmor10c", "marmor10d"],
                    ["marmor10e", "marmor10f", "marmor10g", "marmor10h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor11: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor11.png",
                matrix: [
                    ["marmor11a", "marmor11b", "marmor11c", "marmor11d"],
                    ["marmor11e", "marmor11f", "marmor11g", "marmor11h"],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            marmor12: {
                columns: 4,
                file: "/images/cosmetics/armors/marmor12.png",
                matrix: [
                    ["marmor12a", "marmor12b", "marmor12c", "marmor12d"],
                    ["marmor12e", "marmor12f", null, null],
                ],
                rows: 2,
                size: "normal",
                type: "armor",
            },
            mask1: {
                columns: 25,
                file: "/images/cosmetics/beardo/mask1.png?v=2",
                matrix: [
                    [
                        "mask100",
                        "mask101",
                        "mask102",
                        "mask103",
                        "mask104",
                        "mask105",
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                        null,
                    ],
                ],
                rows: 1,
                type: "beard",
            },
            mbody1: {
                columns: 4,
                file: "/images/cosmetics/armors/mbody1.png?v=2",
                matrix: [
                    ["mbody1a", "mbody1b", "mbody1c", "mbody1d"],
                    ["mbody1e", "mbody1f", "mbody1g", "mbody1h"],
                ],
                rows: 2,
                size: "normal",
                type: "body",
            },
            mbody2: {
                columns: 4,
                file: "/images/cosmetics/armors/mbody2.png?v=6",
                matrix: [
                    ["mbody2a", "mbody2b", "mbody2c", "mbody2d"],
                    ["mbody2e", "mbody2f", "mbody2g", "mbody2h"],
                ],
                rows: 2,
                size: "normal",
                type: "body",
            },
            mbody3: {
                columns: 4,
                file: "/images/cosmetics/armors/mbody3.png?v=3",
                matrix: [
                    ["mbody3a", "mbody3b", "mbody3c", "mbody3d"],
                    ["mbody3e", "mbody3f", "mbody3g", "mbody3h"],
                ],
                rows: 2,
                size: "normal",
                type: "body",
            },
            mbody4: {
                columns: 4,
                file: "/images/cosmetics/armors/mbody4.png?v=3",
                matrix: [
                    ["mbody4a", "mbody4b", "mbody4c", "mbody4d"],
                    ["mbody4e", "mbody4f", "mbody4g", "mbody4h"],
                ],
                rows: 2,
                size: "normal",
                type: "body",
            },
            mbody5: {
                columns: 4,
                file: "/images/cosmetics/armors/mbody5.png?v=3",
                matrix: [
                    ["mbody5a", "mbody5b", "mbody5c", "mbody5d"],
                    ["mbody5e", "mbody5f", "mbody5g", "mbody5h"],
                ],
                rows: 2,
                size: "normal",
                type: "body",
            },
            mbody6: {
                columns: 4,
                file: "/images/cosmetics/armors/mbody6.png",
                matrix: [
                    ["mbody6a", "mbody6b", "mbody6c", null],
                    [null, null, null, null],
                ],
                rows: 2,
                size: "normal",
                type: "body",
            },
            mbw: {
                columns: 1,
                file: "/images/cosmetics/skins/mbw.png",
                matrix: [["mbw"]],
                rows: 1,
                size: "normal",
                type: "skin",
            },
            mchar16: {
                columns: 4,
                file: "/images/all_characters/mchar16.png",
                matrix: [
                    ["mchar16a", "mchar16b", "mchar16c", "mchar16d"],
                    ["mchar16e", "mchar16f", "mchar16g", "mchar16h"],
                ],
                rows: 2,
                size: "normal",
                type: "character",
            },
            mcustom1: {
                columns: 4,
                file: "/images/tiles/monsters/custom1.png?v=6",
                matrix: [
                    ["cgoo", "crabx", "bbpompom", "gscorpion"],
                    ["osnake", "mole", "xscorpion", "arcticbee"],
                ],
                rows: 2,
            },
            mcustom2: {
                columns: 4,
                file: "/images/tiles/monsters/custom2.png?v=5",
                matrix: [
                    ["pinkgooi", "pinkgoo", null, null],
                    ["goldenbat", "wabbit", null, "stoneworm"],
                ],
                rows: 2,
            },
            mechagnome: {
                columns: 1,
                file: "/images/tiles/monsters/mecha_gnome.png",
                matrix: [["mechagnome"]],
                rows: 1,
            },
            military2: {
                columns: 4,
                file: "/images/tiles/characters/military2.png",
                matrix: [
                    [null, "nexus", null, null],
                    [null, null, "bsoldier", null],
                ],
                rows: 2,
            },
            military3: {
                columns: 4,
                file: "/images/tiles/characters/military3.png",
                matrix: [
                    [null, null, null, null],
                    [null, "asoldier", null, null],
                ],
                rows: 2,
            },
            minotaur: {
                columns: 1,
                file: "/images/tiles/monsters/monster_minotaur.png",
                matrix: [["minotaur"]],
                rows: 1,
                skip: 1,
            },
            mmakeup: {
                columns: 14,
                file: "/images/cosmetics/makeup/malemakeup.png?v=4",
                matrix: [
                    [
                        "mmakeup00",
                        "mmakeup01",
                        "mmakeup02",
                        "mmakeup03",
                        "mmakeup04",
                        "mmakeup05",
                        "mmakeup06",
                        "mmakeup07",
                        "mmakeup08",
                        "mmakeup09",
                        "mmakeup10",
                        "mmakeup11",
                        "mmakeup12",
                        "mmakeup13",
                    ],
                ],
                rows: 1,
                type: "head",
            },
            monsterbird1: {
                columns: 1,
                file: "/images/tiles/monsters/monster_bird1.png",
                matrix: [["bigbird"]],
                rows: 1,
            },
            monsterbird2: {
                columns: 1,
                file: "/images/tiles/monsters/monster_bird2.png",
                matrix: [["blackbird"]],
                rows: 1,
                skip: 1,
            },
            monsterbird3: {
                columns: 1,
                file: "/images/tiles/monsters/monster_bird3.png",
                matrix: [["turkeybird"]],
                rows: 1,
                skip: 1,
            },
            monsterc2: {
                columns: 4,
                file: "/images/tiles/monsters/monsterc2.png",
                matrix: [
                    [null, "ent", null, null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            monsterc6: {
                columns: 4,
                file: "/images/tiles/monsters/monsterc6.png?v=2",
                matrix: [
                    ["prat", "pppompom", "spompom", "mighty"],
                    ["slither", "deadgob", "pinkgoblin", "red"],
                ],
                rows: 2,
            },
            monsters1: {
                columns: 4,
                file: "/images/tiles/monsters/monster1.png",
                matrix: [
                    ["goo", "rat", "spider", "scorpion"],
                    ["bloodworm", "snake", "bee", "bat"],
                ],
                rows: 2,
            },
            monsters2: {
                columns: 4,
                file: "/images/tiles/monsters/monster2.png?v=3",
                matrix: [
                    ["crab", "tortoise", "squig", "croc"],
                    ["frog", "squigtoad", "poisio", "armadillo"],
                ],
                rows: 2,
            },
            monsters3: {
                columns: 4,
                file: "/images/tiles/monsters/monster3c.png",
                matrix: [
                    ["minimush", "midimush", "plantoid", "uglyplant"],
                    ["iceroamer", "fireroamer", "chestm", "chestx"],
                ],
                rows: 2,
            },
            monsters4: {
                columns: 4,
                file: "/images/tiles/monsters/monster4.png",
                matrix: [
                    ["ghost", null, null, "skeletor"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            mrgreen: { columns: 1, file: "/images/tiles/monsters/green.png", matrix: [["mrgreen"]], rows: 1 },
            mrpumpkin: { columns: 1, file: "/images/tiles/monsters/mr_pumpkin.png", matrix: [["mrpumpkin"]], rows: 1 },
            mskin1: {
                columns: 4,
                file: "/images/cosmetics/skins/mskin1.png",
                matrix: [
                    ["mskin1a", "mskin1b", "mskin1c", "mskin1d"],
                    ["mskin1e", "mskin1f", "mskin1g", "mskin1h"],
                ],
                rows: 2,
                size: "normal",
                type: "skin",
            },
            mystics: {
                columns: 4,
                file: "/images/tiles/characters/mystics.png",
                matrix: [["mm_blue", "mf_blue", "mm_yellow", "mf_yellow"]],
                rows: 1,
            },
            newyear_tree: {
                columns: 1,
                file: "/images/tiles/characters/others/newyear_tree.png",
                matrix: [["newyear_tree"]],
                rows: 1,
                type: "animation",
            },
            nfmakeup: {
                columns: 23,
                file: "/images/cosmetics/makeup/female_makeup.png",
                matrix: [
                    [
                        "nfmakeup00",
                        "nfmakeup01",
                        "nfmakeup02",
                        "nfmakeup03",
                        "nfmakeup04",
                        "nfmakeup05",
                        "nfmakeup06",
                        "nfmakeup07",
                        "nfmakeup08",
                        "nfmakeup09",
                        "nfmakeup10",
                        "nfmakeup11",
                        "nfmakeup12",
                        "nfmakeup13",
                        "nfmakeup14",
                        "nfmakeup15",
                        "nfmakeup16",
                        "nfmakeup17",
                        "nfmakeup18",
                        "nfmakeup19",
                        "nfmakeup20",
                        "nfmakeup21",
                        "nfmakeup22",
                    ],
                ],
                rows: 1,
                type: "head",
            },
            nmmakeup: {
                columns: 21,
                file: "/images/cosmetics/makeup/male_makeup.png",
                matrix: [
                    [
                        "nmmakeup00",
                        "nmmakeup01",
                        "nmmakeup02",
                        "nmmakeup03",
                        "nmmakeup04",
                        "nmmakeup05",
                        "nmmakeup06",
                        "nmmakeup07",
                        "nmmakeup08",
                        "nmmakeup09",
                        "nmmakeup10",
                        "nmmakeup11",
                        "nmmakeup12",
                        "nmmakeup13",
                        "nmmakeup14",
                        "nmmakeup15",
                        "nmmakeup16",
                        "nmmakeup17",
                        "nmmakeup18",
                        "nmmakeup19",
                        "nmmakeup20",
                    ],
                ],
                rows: 1,
                type: "head",
            },
            npc1: {
                columns: 4,
                file: "/images/tiles/characters/npc1.png",
                matrix: [
                    ["gcitizen", "oldcitizen", null, null],
                    ["fisherman", null, "gemmerchant", null],
                ],
                rows: 2,
            },
            npc3: {
                columns: 4,
                file: "/images/tiles/characters/npc3.png",
                matrix: [
                    [null, "mailman", null, null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            npc4: {
                columns: 4,
                file: "/images/tiles/characters/npc4.png",
                matrix: [
                    ["lady1", "lady2", "gabrielle", "gabriella"],
                    ["lady3", null, "lady4", null],
                ],
                rows: 2,
            },
            npc5: {
                columns: 4,
                file: "/images/tiles/characters/npc5.png",
                matrix: [
                    ["npcc", "lmerchant", "mmerchant", "purplelady"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            npc6: {
                columns: 4,
                file: "/images/tiles/characters/npc6.png",
                matrix: [
                    ["showoff", "fmerchant", "npc63", "llady"],
                    ["renaldo", null, "lucy", null],
                ],
                rows: 2,
            },
            numakeup: {
                columns: 24,
                file: "/images/cosmetics/makeup/unisex_makeup.png",
                matrix: [
                    [
                        "numakeup00",
                        "numakeup01",
                        "numakeup02",
                        "numakeup03",
                        "numakeup04",
                        "numakeup05",
                        "numakeup06",
                        "numakeup07",
                        "numakeup08",
                        "numakeup09",
                        "numakeup10",
                        "numakeup11",
                        "numakeup12",
                        "numakeup13",
                        "numakeup14",
                        "numakeup15",
                        "numakeup16",
                        "numakeup17",
                        "numakeup18",
                        "numakeup19",
                        "numakeup20",
                        "numakeup21",
                        "numakeup22",
                        "numakeup23",
                    ],
                ],
                rows: 1,
                type: "head",
            },
            phoenix: { columns: 1, file: "/images/tiles/monsters/monster_phoenix.png", matrix: [["phoenix"]], rows: 1 },
            raptor1: {
                columns: 1,
                file: "/images/tiles/monsters/monster_raptor1.png",
                matrix: [["greenlizard"]],
                rows: 1,
                skip: 1,
            },
            raptor2: {
                columns: 1,
                file: "/images/tiles/monsters/monster_raptor2.png",
                matrix: [["redlizard"]],
                rows: 1,
                skip: 1,
            },
            rharpy: { columns: 1, file: "/images/tiles/monsters/harpy_a_1.png", matrix: [["rharpy"]], rows: 1 },
            rharpy_fly: {
                columns: 1,
                file: "/images/tiles/monsters/harpy_a_fly_1.png",
                matrix: [["rharpy_fly"]],
                rows: 1,
            },
            robots: {
                columns: 4,
                file: "/images/tiles/monsters/robots.png",
                matrix: [
                    [null, null, "zapper0", null],
                    [null, null, null, "fieldgen0"],
                ],
                rows: 2,
            },
            robots1: {
                columns: 4,
                file: "/images/tiles/monsters/robots_walkin_B_1.png?v=2",
                matrix: [
                    ["goldenbot", "sparkbot", "targetron", null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            rudolph: { columns: 1, file: "/images/tiles/monsters/rudolphi.png", matrix: [["rudolph"]], rows: 1 },
            sarmor1: {
                columns: 4,
                file: "/images/cosmetics/armors/sarmor1.png?v=2",
                matrix: [
                    ["sarmor1a", "sarmor1b", "sarmor1c", "sarmor1d"],
                    ["sarmor1e", "sarmor1f", "sarmor1g", "sarmor1h"],
                ],
                rows: 2,
                size: "small",
                type: "armor",
            },
            sarmor2: {
                columns: 4,
                file: "/images/cosmetics/armors/sarmor2.png?v=2",
                matrix: [
                    ["sarmor2a", "sarmor2b", "sarmor2c", "sarmor2d"],
                    [null, null, null, null],
                ],
                rows: 2,
                size: "small",
                type: "armor",
            },
            sbody1: {
                columns: 4,
                file: "/images/cosmetics/armors/sbody1.png?v=4",
                matrix: [
                    ["sbody1a", "sbody1b", "sbody1c", "sbody1d"],
                    ["sbody1e", null, null, null],
                ],
                rows: 2,
                size: "small",
                type: "body",
            },
            schar7: {
                columns: 4,
                file: "/images/all_characters/schar7.png",
                matrix: [
                    ["schar7a", "schar7b", "schar7c", "schar7d"],
                    ["schar7e", "schar7f", "schar7g", "schar7h"],
                ],
                rows: 2,
                size: "small",
                type: "character",
            },
            ship1: {
                columns: 1,
                file: "/images/tiles/characters/others/ship2.png",
                matrix: [["ship"]],
                rows: 1,
                type: "animation",
            },
            slenderman: {
                columns: 1,
                file: "/images/tiles/monsters/slenderman.png",
                matrix: [["slenderman"]],
                rows: 1,
            },
            smakeup: {
                columns: 1,
                file: "/images/cosmetics/makeup/smakeup.png",
                matrix: [["smakeup00"]],
                rows: 1,
                type: "head",
            },
            snowman: { columns: 1, file: "/images/tiles/monsters/snowman.png", matrix: [["snowman"]], rows: 1 },
            spiderqueens: {
                columns: 2,
                file: "/images/tiles/monsters/giantspider.png",
                matrix: [
                    ["spiderbl", "spiderbr"],
                    ["spiderp", "spiderr"],
                ],
                rows: 2,
            },
            sskin1: {
                columns: 4,
                file: "/images/cosmetics/skins/sskin1.png",
                matrix: [
                    ["sskin1a", "sskin1b", "sskin1c", "sskin1d"],
                    ["sskin1e", "sskin1f", "sskin1g", "sskin1h"],
                ],
                rows: 2,
                size: "small",
                type: "skin",
            },
            stompy: { columns: 1, file: "/images/tiles/monsters/stompy3.png", matrix: [["stompy"]], rows: 1 },
            swa: {
                columns: 4,
                file: "/images/tiles/characters/sheet_winnersa.png",
                matrix: [
                    [null, "scarf", null, null],
                    [null, null, "proft", "twig"],
                ],
                rows: 2,
            },
            swb: {
                columns: 4,
                file: "/images/tiles/characters/sheet_winnersb.png",
                matrix: [
                    [null, null, null, "bobo"],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            tail1: {
                columns: 1,
                file: "/images/cosmetics/tails/wolftail.png",
                matrix: [["tail100"]],
                rows: 1,
                type: "tail",
            },
            tail2: {
                columns: 1,
                file: "/images/cosmetics/tails/wolftail2.png",
                matrix: [["tail200"]],
                rows: 1,
                type: "tail",
            },
            tail3: {
                columns: 1,
                file: "/images/cosmetics/tails/wolftail3.png",
                matrix: [["tail300"]],
                rows: 1,
                type: "tail",
            },
            test: {
                columns: 4,
                file: "/images/tiles/characters/ninja_turtles.png",
                matrix: [["t1", "test", "t3", "t4"]],
                rows: 1,
            },
            tiger: { columns: 1, file: "/images/tiles/monsters/tiger.png", matrix: [["tiger"]], rows: 1 },
            tinyfairies: {
                columns: 4,
                file: "/images/tiles/monsters/tinyfairies.png",
                matrix: [
                    ["tinyp", null, null, null],
                    [null, null, null, null],
                ],
                rows: 2,
            },
            treant: {
                columns: 1,
                file: "/images/tiles/monsters/monster_treant.png",
                matrix: [["treant"]],
                rows: 1,
                skip: 1,
            },
            tristone_f: {
                columns: 4,
                file: "/images/tiles/characters/tristone_f.png",
                matrix: [
                    ["tf_pink", "tf_blue", "tf_green", "tf_orange"],
                    ["tf_purple", null, null, null],
                ],
                rows: 2,
            },
            tristone_m: {
                columns: 4,
                file: "/images/tiles/characters/tristone_m.png",
                matrix: [
                    ["tm_red", "tm_brown", "tm_yellow", "tm_green"],
                    ["tm_gray", "tm_blue", "tm_purple", "tm_white"],
                ],
                rows: 2,
            },
            vampires: {
                columns: 4,
                file: "/images/tiles/monsters/vampire2d.png",
                matrix: [
                    ["mvampire", "fvampire", null, null],
                    [null, null, "vbat", null],
                ],
                rows: 2,
            },
            wings1: {
                columns: 5,
                file: "/images/cosmetics/wings/wings1.png",
                matrix: [["wings100", "wings101", "wings102", "wings103", "wings104"]],
                rows: 1,
                type: "s_wings",
            },
            wings3: {
                columns: 5,
                file: "/images/cosmetics/wings/wings3.png?v=2",
                matrix: [["wings300", "wings301", "wings302", "wings303", "wings304"]],
                rows: 1,
                type: "s_wings",
            },
            wolf1: { columns: 1, file: "/images/tiles/monsters/monster_wolf1.png", matrix: [["wolf"]], rows: 1 },
            wolf2: { columns: 1, file: "/images/tiles/monsters/monster_wolf2.png", matrix: [["wolfie"]], rows: 1 },
            xschar2: {
                columns: 4,
                file: "/images/all_characters/xschar2.png",
                matrix: [
                    ["xschar2a", "xschar2b", "xschar2c", "xschar2d"],
                    ["xschar2e", "xschar2f", "xschar2g", "xschar2h"],
                ],
                rows: 2,
                size: "xsmall",
                type: "character",
            },
            xxschar2: {
                columns: 4,
                file: "/images/all_characters/xxschar2.png",
                matrix: [
                    ["xxschar2a", "xxschar2b", "xxschar2c", "xxschar2d"],
                    ["xxschar2e", "xxschar2f", "xxschar2g", "xxschar2h"],
                ],
                rows: 2,
                size: "xxsmall",
                type: "character",
            },
        },
    }
    expect(G_sprites).toBeDefined()
})
