import type { GData } from "./adventureland-data"

/**
 * The following is from http://adventure.land/data.js, version 17120 (2026-09-21)
 * It is used to confirm type correctness
 */

test("G.cosmetics type validation", async () => {
    const G_cosmetics: Pick<GData, "cosmetics"> = {
        cosmetics: {
            back: {
                backpacks00: 1,
                backpacks01: 1,
                backpacks02: 1,
                backpacks03: 1,
                backpacks04: 1,
                backpacks200: 1,
                backpacks201: 1,
            },
            bundle: {
                blackw: ["mbody6b", "mbody6c", "blackhead"],
                headaliens: ["makeup101", "makeup103"],
                headbeards: [
                    "makeup104",
                    "makeup106",
                    "makeup108",
                    "makeup110",
                    "makeup112",
                    "mmakeup08",
                    "mmakeup09",
                    "mmakeup10",
                    "fmakeup09",
                    "fmakeup10",
                ],
                headbones: ["makeup132", "makeup134", "fmakeup12"],
                headcolors: [
                    "makeup100",
                    "makeup102",
                    "makeup107",
                    "makeup109",
                    "makeup111",
                    "makeup113",
                    "makeup114",
                    "makeup118",
                    "makeup121",
                    "makeup122",
                    "makeup123",
                    "makeup125",
                    "makeup127",
                    "makeup128",
                    "makeup130",
                    "makeup133",
                    "makeup135",
                    "makeup136",
                    "makeup138",
                    "makeup140",
                    "mmakeup01",
                    "mmakeup02",
                    "nmmakeup00",
                ],
                headcolorsf: [
                    "fmakeup00",
                    "nfmakeup01",
                    "nfmakeup02",
                    "nfmakeup03",
                    "nfmakeup04",
                    "nfmakeup05",
                    "nfmakeup06",
                    "nfmakeup07",
                    "nfmakeup08",
                    "nfmakeup09",
                    "nfmakeup10",
                    "nfmakeup11",
                    "nfmakeup12",
                    "nfmakeup13",
                    "nfmakeup14",
                    "nfmakeup15",
                    "nfmakeup16",
                    "nfmakeup17",
                    "nfmakeup18",
                    "nfmakeup19",
                    "nfmakeup20",
                    "nfmakeup21",
                    "nfmakeup22",
                ],
                headelves: ["makeup116", "mmakeup03", "fmakeup04"],
                headfangs: ["makeup101", "makeup103", "makeup129", "fmakeup05"],
                headfins: ["makeup115", "makeup131"],
                headhorns: ["makeup124", "makeup126", "makeup137", "makeup139", "mmakeup06", "fmakeup07", "fmakeup11"],
                headmice: ["makeup124", "makeup126", "mmakeup06", "fmakeup07"],
                headorcs: ["makeup129", "fmakeup05"],
                headroundblue: ["makeup118", "makeup122", "makeup133"],
                headroundbrown: ["makeup135", "makeup138", "mmakeup01", "mmakeup02"],
                headroundgold: ["makeup113", "makeup125", "nmmakeup00"],
                headroundgreen: ["makeup100", "makeup102", "makeup114", "makeup128"],
                headroundpale: ["makeup111", "makeup123", "makeup127", "makeup136"],
                headroundred: ["makeup109", "makeup121"],
                headroundslate: ["makeup107", "makeup140"],
                headskulls: ["makeup119", "makeup132", "makeup134", "fmakeup08", "fmakeup12"],
                headsoftblue: ["nfmakeup17", "nfmakeup18"],
                headsoftbrightgreen: ["nfmakeup12", "nfmakeup13"],
                headsoftbrown: ["nfmakeup04", "nfmakeup05", "nfmakeup06", "nfmakeup07"],
                headsoftgold: ["nfmakeup08", "nfmakeup14"],
                headsoftgreen: ["nfmakeup12", "nfmakeup13", "nfmakeup19"],
                headsoftmuted: [
                    "nfmakeup15",
                    "nfmakeup16",
                    "nfmakeup17",
                    "nfmakeup18",
                    "nfmakeup19",
                    "nfmakeup20",
                    "nfmakeup21",
                    "nfmakeup22",
                ],
                headsoftpale: ["nfmakeup15", "nfmakeup16", "nfmakeup20"],
                headsoftred: ["nfmakeup09", "nfmakeup10"],
                headsoftslate: ["nfmakeup21", "nfmakeup22"],
                headsoftwarm: ["fmakeup00", "nfmakeup01", "nfmakeup02", "nfmakeup03"],
                headwolves: ["makeup137", "makeup139", "fmakeup11"],
                headyetis: ["makeup119", "fmakeup08"],
                pinkb: ["mbody2g", "mbody2h"],
                rogueb: ["sbody1c", "sarmor1h"],
            },
            default_beard_position: 0,
            default_face_position: 7,
            default_hair_place: 7,
            default_hat_place: 7,
            default_head_place: 7,
            default_makeup_position: 0,
            gravestone: {
                gravestone: 19,
                gravestonea: 19,
                xgravestone0: 21,
                xgravestone1: 21,
                xgravestone2: 21,
                xgravestone3: 21,
                xgravestone4: 21,
            },
            hair: {
                bwhair: [-2, 1],
                hairdo100: [0, 0],
                hairdo101: [0, 1],
                hairdo102: [0, 2],
                hairdo103: [0, 0],
                hairdo104: [0, 1],
                hairdo105: [0, 0],
                hairdo106: [0, 1],
                hairdo107: [0, 1],
                hairdo108: [0, 1],
                hairdo109: [0, 1],
                hairdo110: [0, 1],
                hairdo111: [0, 0],
                hairdo112: [0, 0],
                hairdo113: [0, 0],
                hairdo114: [0, 0],
                hairdo115: [0, 3],
                hairdo116: [0, 1],
                hairdo117: [0, 2],
                hairdo118: [0, 2],
                hairdo119: [0, 1],
                hairdo120: [0, 1],
                hairdo121: [0, 2],
                hairdo122: [0, 2],
                hairdo123: [0, 0],
                hairdo124: [0, 0],
                hairdo200: [0, 1],
                hairdo201: [0, 1],
                hairdo202: [0, 2],
                hairdo203: [0, 1],
                hairdo204: [0, 1],
                hairdo205: [0, 2],
                hairdo206: [0, 0],
                hairdo207: [0, 0],
                hairdo208: [0, 0],
                hairdo209: [0, 1],
                hairdo210: [0, 0],
                hairdo211: [0, 1],
                hairdo212: [0, 0],
                hairdo213: [0, 2],
                hairdo214: [0, 0],
                hairdo215: [0, 0],
                hairdo216: [0, 1],
                hairdo217: [0, 0],
                hairdo218: [0, 0],
                hairdo219: [0, 0],
                hairdo220: [0, 0],
                hairdo221: [0, 0],
                hairdo222: [0, 0],
                hairdo223: [0, 0],
                hairdo224: [0, 3],
                hairdo300: [0, 0],
                hairdo301: [0, 1],
                hairdo302: [0, 0],
                hairdo303: [0, 1],
                hairdo304: [0, 1],
                hairdo305: [0, 0],
                hairdo306: [0, 0],
                hairdo307: [0, 1],
                hairdo308: [0, 0],
                hairdo309: [0, 1],
                hairdo310: [0, 0],
                hairdo311: [0, 0],
                hairdo312: [0, 0],
                hairdo313: [0, 0],
                hairdo314: [0, 0],
                hairdo315: [0, 0],
                hairdo316: [0, 2],
                hairdo317: [0, 0],
                hairdo318: [0, 0],
                hairdo319: [0, 0],
                hairdo320: [0, 0],
                hairdo321: [0, 1],
                hairdo322: [0, 0],
                hairdo323: [0, 0],
                hairdo324: [0, 0],
                hairdo400: [0, 1],
                hairdo401: [0, 1],
                hairdo402: [0, 4],
                hairdo403: [0, 0],
                hairdo404: [0, 0],
                hairdo405: [0, 3],
                hairdo406: [0, 0],
                hairdo407: [0, 0],
                hairdo408: [0, 0],
                hairdo409: [0, 0],
                hairdo410: [0, 0],
                hairdo411: [0, 0],
                hairdo412: [0, 2],
                hairdo413: [0, 3],
                hairdo414: [0, 0],
                hairdo415: [0, 0],
                hairdo416: [0, 0],
                hairdo417: [0, 0],
                hairdo418: [0, 0],
                hairdo419: [0, 3],
                hairdo420: [0, 2],
                hairdo421: [0, 0],
                hairdo422: [0, 0],
                hairdo423: [0, 0],
                hairdo424: [0, 0],
                hairdo500: [0, 0],
                hairdo501: [0, 1],
                hairdo502: [0, 2],
                hairdo503: [0, 3],
                hairdo504: [0, 0],
                hairdo505: [0, 0],
                hairdo506: [0, 0],
                hairdo507: [0, 1],
                hairdo508: [0, 2],
                hairdo509: [0, 2],
                hairdo510: [0, 2],
                hairdo511: [0, 3],
                hairdo512: [0, 1],
                hairdo513: [0, 1],
                hairdo514: [0, 0],
                hairdo515: [0, 0],
                hairdo516: [0, 1],
                hairdo517: [0, 2],
                hairdo518: [0, 1],
                hairdo519: [0, 0],
                hairdo520: [0, 0],
                hairdo521: [0, 1],
                hairdo522: [0, 1],
                hairdo523: [0, 1],
                hairdo600: [0, 1],
                hairdo601: [0, 1],
                hairdo602: [0, 1],
                hairdo603: [0, 1],
                hairdo604: [0, 0],
                hairdo605: [0, 0],
            },
            hat: { hat100: 0 },
            hat_animation: { aniv2: 160, gcandle: 180, halo: 200 },
            head: {
                blackhead: ["sskin1d", "mskin1d", "lskin1d"],
                bwhead: ["sskin1e", "mbw", "lskin1d"],
                cyclops0: ["sskin1a", "mskin1a", "lskin1a", 1],
                eyehead0: ["sskin1e", "mskin1e", "lskin1e"],
                fmakeup00: ["sskin1a", "mskin1a", "lskin1a"],
                fmakeup02: ["sskin1b", "mskin1b", "lskin1b"],
                fmakeup03: ["sskin1b", "mskin1b", "lskin1b"],
                fmakeup04: ["sskin1a", "mskin1a", "lskin1a"],
                fmakeup05: ["sskin1c", "mskin1c", "lskin1c"],
                fmakeup06: ["sskin1g", "mskin1g", "lskin1a"],
                fmakeup07: ["sskin1e", "mskin1e", "lskin1d", 1],
                fmakeup08: ["sskin1e", "mskin1e", "lskin1d", 1],
                fmakeup09: ["sskin1e", "mskin1e", "lskin1d", 1],
                fmakeup10: ["sskin1b", "mskin1b", "lskin1b", 1],
                fmakeup11: ["sskin1b", "mskin1b", "lskin1b", 1],
                fmakeup12: ["sskin1e", "mskin1e", "lskin1d", 1],
                lanternhead0: ["sskin1d", "mskin1d", "lskin1d"],
                lavaglasshead0: ["sskin1b", "mskin1b", "lskin1b", 0],
                makeup100: ["sskin1e", "mskin1e", "lskin1d"],
                makeup101: ["sskin1e", "mskin1e", "lskin1d", 1],
                makeup102: ["sskin1c", "mskin1c", "lskin1c"],
                makeup103: ["sskin1c", "mskin1c", "lskin1c", 1],
                makeup104: ["sskin1b", "mskin1b", "lskin1b", 1],
                makeup105: ["sskin1b", "mskin1b", "lskin1b"],
                makeup106: ["sskin1d", "mskin1d", "lskin1d", 1],
                makeup107: ["sskin1d", "mskin1d", "lskin1d"],
                makeup108: ["sskin1b", "mskin1b", "lskin1b", 1],
                makeup109: ["sskin1b", "mskin1b", "lskin1b"],
                makeup110: ["sskin1e", "mskin1e", "lskin1d", 1],
                makeup111: ["sskin1e", "mskin1e", "lskin1d"],
                makeup112: ["sskin1f", "mskin1f", "lskin1a", 1],
                makeup113: ["sskin1f", "mskin1f", "lskin1a"],
                makeup114: ["sskin1c", "mskin1c", "lskin1c"],
                makeup115: ["sskin1c", "mskin1c", "lskin1c"],
                makeup116: ["sskin1a", "mskin1a", "lskin1a", 1],
                makeup117: ["sskin1a", "mskin1a", "lskin1a"],
                makeup118: ["sskin1e", "mskin1e", "lskin1d"],
                makeup119: ["sskin1e", "mskin1e", "lskin1d", 1],
                makeup120: ["sskin1h", "mskin1h", "lskin1d", 1],
                makeup121: ["sskin1h", "mskin1h", "lskin1d"],
                makeup122: ["sskin1d", "mskin1d", "lskin1d"],
                makeup123: ["sskin1e", "mskin1e", "lskin1d"],
                makeup124: ["sskin1b", "mskin1b", "lskin1b"],
                makeup125: ["sskin1b", "mskin1b", "lskin1b"],
                makeup126: ["sskin1e", "mskin1e", "lskin1d"],
                makeup127: ["sskin1e", "mskin1e", "lskin1d"],
                makeup128: ["sskin1c", "mskin1c", "lskin1c"],
                makeup129: ["sskin1c", "mskin1c", "lskin1c", 1],
                makeup130: ["sskin1g", "mskin1g", "lskin1a"],
                makeup131: ["sskin1g", "mskin1g", "lskin1a"],
                makeup132: ["sskin1b", "mskin1b", "lskin1b", 1],
                makeup133: ["sskin1e", "mskin1e", "lskin1d"],
                makeup134: ["sskin1e", "mskin1e", "lskin1d", 1],
                makeup135: ["sskin1b", "mskin1b", "lskin1b"],
                makeup136: ["sskin1e", "mskin1e", "lskin1d"],
                makeup137: ["sskin1b", "mskin1b", "lskin1b"],
                makeup138: ["sskin1b", "mskin1b", "lskin1b"],
                makeup139: ["sskin1d", "mskin1d", "lskin1d"],
                makeup140: ["sskin1d", "mskin1d", "lskin1d"],
                mimichead0: ["sskin1b", "mskin1b", "lskin1b"],
                mmakeup01: ["sskin1b", "mskin1b", "lskin1b"],
                mmakeup02: ["sskin1b", "mskin1b", "lskin1b"],
                mmakeup03: ["sskin1a", "mskin1a", "lskin1a"],
                mmakeup04: ["sskin1c", "mskin1c", "lskin1c"],
                mmakeup05: ["sskin1c", "mskin1c", "lskin1c"],
                mmakeup06: ["sskin1b", "mskin1b", "lskin1b"],
                mmakeup07: ["sskin1h", "mskin1h", "lskin1d", 1],
                mmakeup08: ["sskin1b", "mskin1b", "lskin1b"],
                mmakeup09: ["sskin1d", "mskin1d", "lskin1d"],
                mmakeup10: ["sskin1f", "mskin1f", "lskin1a", 1],
                mmakeup11: ["sskin1d", "mskin1d", "lskin1d"],
                mmakeup12: ["sskin1b", "mskin1b", "lskin1b"],
                mmakeup13: ["sskin1d", "mskin1d", "lskin1d"],
                nfmakeup01: ["sskin1a", "mskin1a", "lskin1a"],
                nfmakeup02: ["sskin1a", "mskin1a", "lskin1a"],
                nfmakeup03: ["sskin1a", "mskin1a", "lskin1a"],
                nfmakeup04: ["sskin1b", "mskin1b", "lskin1b"],
                nfmakeup05: ["sskin1b", "mskin1b", "lskin1b"],
                nfmakeup06: ["sskin1b", "mskin1b", "lskin1b"],
                nfmakeup07: ["sskin1b", "mskin1b", "lskin1b"],
                nfmakeup08: ["sskin1b", "mskin1b", "lskin1b"],
                nfmakeup09: ["sskin1b", "mskin1b", "lskin1b"],
                nfmakeup10: ["sskin1h", "mskin1h", "lskin1b"],
                nfmakeup11: ["sskin1g", "mskin1g", "lskin1a"],
                nfmakeup12: ["sskin1c", "mskin1c", "lskin1c"],
                nfmakeup13: ["sskin1c", "mskin1c", "lskin1c"],
                nfmakeup14: ["sskin1f", "mskin1f", "lskin1a"],
                nfmakeup15: ["sskin1e", "mskin1e", "lskin1e"],
                nfmakeup16: ["sskin1e", "mskin1e", "lskin1e"],
                nfmakeup17: ["sskin1e", "mskin1e", "lskin1e"],
                nfmakeup18: ["sskin1d", "mskin1d", "lskin1d"],
                nfmakeup19: ["sskin1e", "mskin1e", "lskin1e"],
                nfmakeup20: ["sskin1e", "mskin1e", "lskin1e"],
                nfmakeup21: ["sskin1d", "mskin1d", "lskin1d"],
                nfmakeup22: ["sskin1d", "mskin1d", "lskin1d"],
                nmmakeup00: ["sskin1a", "mskin1a", "lskin1a"],
                slimehead0: ["sslimeskin", "mslimeskin", "lslimeskin", 1],
                smakeup00: ["sskin1a", "mskin1a", "lskin1a", -1],
                stormhead0: ["sskin1d", "mskin1d", "lskin1d", 0],
            },
            head_animation: { lavaglasshead0: 160, stormhead0: 220 },
            head_y: { mbody4b: 1 },
            map: { old: "new" },
            no_upper: [],
            prop: {
                bathat: ["manim", "fast"],
                hairdo604: ["no_hat"],
                hairdo605: ["no_hat"],
                lchar1b: ["hair"],
                lchar1d: ["bulky"],
                lchar1e: ["female"],
                lchar1f: ["no_upper"],
                lchar1g: ["no_upper"],
                lchar1h: ["bulky", "hair"],
                marmor12b: ["slender"],
                marmor12c: ["covers", "no_hair"],
                marmor12d: ["covers", "no_hair"],
                mbody2g: ["covers", "no_hair"],
                mbody5e: ["covers", "no_hair"],
                mbody5f: ["covers", "no_hair"],
                mbody6b: ["covers", "no_hair"],
                mbody6c: ["covers"],
            },
        },
    }
    expect(G_cosmetics).toBeDefined()
})
