import type { GData } from "./adventureland-data"

/**
 * The following is from http://adventure.land/data.js, version 831 (2025-12-23)
 * It is used to confirm type correctness
 */

test("G.conditions type validation", async () => {
    const G_conditions: Pick<GData, "conditions"> = {
        conditions: {
            authfail: {
                debuff: true,
                explanation:
                    "Your account has failed an internal authorization routine. This might've happened if you haven't logged on from Steam or Mac App Store since this new system was implemented. So just opening the non-web game client once, starting one character, hanging 1-2 minutes on a server and logging out will be enough to correct this mistake. If it persists unexpectedly email hello@adventure.land.",
                gold: -85,
                luck: -85,
                name: "Authorization Failure",
                persistent: true,
                skin: "notverified",
                technical: true,
                ui: true,
                xp: -20,
            },
            blink: {
                explanation: "Blink in progress",
                name: "Blinking",
                skin: "condition_positive",
            },
            block: {
                debuff: true,
                explanation: "After engaging in PVP, blocked from safely leaving!",
                name: "PVP Block",
                persistent: true,
                skin: "condition_neutral",
            },
            burned: {
                debuff: true,
                defense: "firesistance",
                explanation: "Burns the target for damage equal to its intensity per second.",
                interval: 210,
                name: "Burned",
                skin: "fireblade",
                ui: true,
            },
            charging: {
                duration: 3200,
                explanation: "A short burst of speed.",
                name: "Charging",
                skin: "condition_positive",
                speed: 30,
            },
            charmed: {
                debuff: true,
                duration: 30000,
                explanation: "Mellow like a warm kitty.",
                name: "Charmed",
                skin: "charmer",
                ui: true,
            },
            cursed: {
                debuff: true,
                duration: 5000,
                explanation: "Reduces damage output and speed by 20%. Increases damage taken by 20%.",
                incdmgamp: 20,
                name: "Cursed",
                output: -20,
                skin: "condition_bad",
                speed: -20,
            },
            dampened: {
                debuff: true,
                duration: 300,
                explanation: "Can't blink or teleport.",
                name: "Dampened",
                skin: "dampened",
            },
            darkblessing: {
                buff: true,
                duration: 8000,
                explanation: "Increases damage output.",
                name: "Dark Blessing",
                output: 25,
                skin: "skill_dbuff",
                ui: true,
            },
            dash: {
                name: "Dashing",
                persistent: true,
                set_speed: 500,
                skin: "condition_positive",
            },
            deepfreezed: {
                blocked: true,
                debuff: true,
                defense: "fzresistance",
                duration: 12000,
                explanation: "Cannot move, attack, heal, or use skills.",
                name: "Deepfreezed",
                skin: "condition_bad",
                ui: true,
            },
            easterluck: {
                buff: true,
                duration: 86400000,
                explanation: "Luck is greatly increased.",
                luck: 100,
                name: "Easter Luck",
                persistent: true,
                skin: "easterluck",
                ui: true,
            },
            eburn: {
                damage: 50,
                debuff: true,
                duration: 12000,
                explanation: "Burns the target with fire essence, dealing damage over time.",
                intensity: "burnd",
                interval: 200,
                name: "Burn",
                skin: "essenceoffire",
                speed: 5,
                ui: true,
            },
            eheal: {
                buff: true,
                duration: 4000,
                explanation: "Heals the target over time using life essence.",
                heal: 200,
                interval: 320,
                name: "Rejuvenate",
                skin: "essenceoflife",
                ui: true,
            },
            energized: {
                buff: true,
                duration: 800,
                explanation: "Gives a brief burst of attack speed.",
                frequency: 80,
                name: "Energized",
                skin: "skill_energize",
                ui: true,
            },
            fingered: {
                blocked: true,
                debuff: true,
                evasion: 96,
                explanation: "Stunned for the duration.",
                name: "Deep Meditation",
                resistance: 1600,
                skin: "condition_neutral",
            },
            fishing: {
                channel: true,
                duration: 15000,
                duration_min: 5000,
                explanation: "Fishing in progress.",
                name: "Fishing",
                skin: "skill_fishing",
            },
            frozen: {
                debuff: true,
                defense: "fzresistance",
                duration: 5000,
                explanation: "Reduces speed by 40 and frequency by 70%.",
                frequencym: 0.3,
                name: "Frozen",
                skin: "frostbow",
                speed: -40,
                ui: true,
            },
            fullguard: {
                armor: 10000,
                buff: true,
                explanation: "Providing maximum resistance and armor.",
                name: "Full Guard",
                persistent: true,
                resistance: 10000,
                skin: "fullguard",
                ui: true,
            },
            fullguardx: {
                avoidance: 99,
                buff: true,
                explanation: "Increasing avoidance to near perfect.",
                name: "Full Guard",
                persistent: true,
                skin: "fullguard",
                ui: true,
            },
            halloween0: {
                buff: true,
                duration: 172800000,
                explanation: "A full-on Halloween blast with tons of XP to haunt your day.",
                gold: 5,
                luck: 5,
                name: "Halloween Spirit",
                persistent: true,
                skin: "halloween0",
                ui: true,
                xp: 100,
            },
            halloween1: {
                buff: true,
                duration: 86400000,
                explanation: "A nice spooky boost to luck and XP.",
                gold: 5,
                luck: 5,
                name: "Halloween Spirit",
                output: 2,
                persistent: true,
                skin: "halloween1",
                ui: true,
                xp: 50,
            },
            halloween2: {
                buff: true,
                duration: 28800000,
                explanation: "A quick touch of Halloween magic to boost luck and gold.",
                gold: 5,
                luck: 5,
                name: "Halloween Spirit",
                output: 3,
                persistent: true,
                skin: "halloween2",
                ui: true,
                xp: 10,
            },
            hardshell: {
                armor: 800,
                buff: true,
                duration: 8000,
                explanation: "Greatly increases armor but limits maximum speed to 10.",
                name: "Hard Shell",
                set_speed: 10,
                skin: "skill_hardshell",
            },
            holidayspirit: {
                buff: true,
                duration: 86400000,
                explanation: "Feel the festive vibes luck, gold, and XP boosted!",
                gold: 20,
                luck: 20,
                name: "Holiday Spirit",
                persistent: true,
                skin: "holidayspirit",
                ui: true,
                xp: 20,
            },
            hopsickness: {
                debuff: true,
                duration: 720000,
                explanation: "You are not in your home server! Go see Bean in Mainland square for a change.",
                gold: -80,
                luck: -80,
                name: "Hop Sickness",
                output: -20,
                persistent: true,
                skin: "condition_bad",
                special: "snakeoil",
                ui: true,
                xp: -80,
            },
            invincible: {
                duration: 6000,
                explanation:
                    "When you spawn in a PVP area. This prevents you from receiving damage or marked as engaged in PVP. If you get attacked, disconnect before this runs out - or fight!",
                name: "Invincible",
                persistent: true,
                skin: "condition_positive",
            },
            invis: {
                buff: true,
                explanation: "Hidden from everyone else until you attack.",
                name: "Invisible",
                skin: "skill_invis",
            },
            licenced: {
                buff: true,
                explanation: "A special, temporary immunity.",
                name: "Licenced to Kill",
                skin: "licence",
                ui: true,
            },
            marked: {
                debuff: true,
                duration: 10000,
                explanation: "Marked by a ranger for death. Receive 10% more damage and can't stealth.",
                incdmgamp: 10,
                name: "Marked",
                skin: "skill_huntersmark",
                ui: true,
            },
            massproduction: {
                buff: true,
                duration: 10000,
                explanation: "Reduces the time of your next upgrade or compound by 50%.",
                name: "Mass Production",
                skin: "skill_massproduction",
                ui: true,
            },
            massproductionpp: {
                buff: true,
                duration: 10000,
                explanation: "Reduces the time of your next upgrade or compound by 90%.",
                name: "Mass Production++",
                skin: "skill_massproductionpp",
                ui: true,
            },
            mcourage: {
                buff: true,
                courage: 5,
                duration: 10000,
                evasion: 40,
                explanation: "Increases speed, evasion, and all types of courage.",
                mcourage: 5,
                name: "Merchant's Courage",
                pcourage: 5,
                skin: "skill_mcourage",
                speed: 25,
                ui: true,
            },
            mfrenzy: {
                buff: true,
                duration: 5000,
                explanation: "Greatly boosts attack speed and output while lowering mana cost.",
                frequency: 800,
                mp_cost: -20,
                name: "Merchant's Frenzy",
                output: 40,
                skin: "skill_mfrenzy",
                ui: true,
            },
            mining: {
                channel: true,
                duration: 15000,
                duration_min: 5000,
                explanation: "Mining in progress.",
                name: "Mining",
                skin: "skill_mining",
            },
            mlifesteal: {
                buff: true,
                duration: 3600000,
                explanation: "Fresh from vampire slaying.",
                lifesteal: 2.5,
                name: "Lifesteal",
                skin: "lifestealscroll",
                ui: true,
            },
            mluck: {
                buff: true,
                duration: 3600000,
                explanation: "Lucked!",
                luck: 12,
                name: "Good Luck",
                persistent: true,
                skin: "buff_luck",
                ui: true,
            },
            monsterhunt: {
                duration: 1800000,
                explanation: "Tracking a target.",
                name: "On The Hunt",
                persistent: true,
                skin: "quest_monsterhunt",
                ui: true,
            },
            mshield: {
                buff: true,
                explanation: "Mana absorbs damage before health.",
                name: "Mana Shield",
                skin: "skill_mshield",
                ui: true,
            },
            newcomersblessing: {
                aura: true,
                duration: 1800000,
                explanation: "Increases luck, gold gain, and experience earned.",
                gold: 10,
                luck: 10,
                name: "Newcomers' Blessing",
                persistent: true,
                skin: "newcomersblessing",
                ui: true,
                xp: 10,
            },
            notverified: {
                debuff: true,
                explanation: "Reduced luck and gold until the associated email address is verified.",
                gold: -25,
                luck: -25,
                name: "Not Verified",
                persistent: true,
                skin: "notverified",
                technical: true,
                ui: true,
            },
            patronsgrace: {
                buff: true,
                duration: 120000,
                explanation: "This server has been graced by a patron's support!",
                gold: 20,
                luck: 5,
                name: "Patron's Grace",
                skin: "patronsgrace",
                speed: 1,
                ui: true,
                xp: 25,
            },
            penalty_cd: {
                debuff: true,
                explanation:
                    "The remaining duration of this condition is added any skill you use. Teleporting adds 3s, magiporting adds around 800ms, some item operations add 100-200ms.",
                name: "Penalty Cooldown",
                skin: "condition_bad",
            },
            phasedout: {
                buff: true,
                duration: 5000,
                evasion: 64,
                explanation: "Decreases attack and movement speed but greatly increases evasion.",
                frequency: -40,
                name: "Phased Out",
                skin: "skill_phaseout",
                speed: -16,
                ui: true,
            },
            pickpocket: {
                channel: true,
                duration: 2200,
                duration_min: 200,
                explanation: "Pickpocket in progress.",
                name: "Pickpocket",
                skin: "skill_pickpocket",
            },
            poisoned: {
                debuff: true,
                defense: "pnresistance",
                duration: 5000,
                explanation:
                    "Reduces attack speed by 10%. All potions are 50% less effective. Healing effects are 75% less effective.",
                frequencym: 0.9,
                healm: 0.25,
                name: "Poison",
                potionsm: 0.5,
                skin: "poison",
            },
            poisonous: {
                buff: true,
                duration: 5000,
                explanation: "Your attacks apply Poison.",
                name: "Poisonous",
                skin: "skill_pcoat",
                ui: true,
            },
            power: {
                buff: true,
                duration: 4000,
                explanation: "Increases attack speed and reduces mana cost.",
                frequency: 360,
                mp_cost: -200,
                name: "Power",
                skin: "powerglove",
                ui: true,
            },
            purifier: {
                buff: true,
                duration: 8000,
                explanation: "Boosts attack speed, damage output, and strength.",
                frequency: 20,
                name: "Purifier",
                output: 20,
                skin: "skill_purify",
                str: 30,
                ui: true,
            },
            reflection: {
                buff: true,
                cap_reflection: 50,
                duration: 5000,
                explanation: "Increases your chance to reflect attacks.",
                name: "Reflective Shield",
                reflection: 20,
                skin: "buff_reflection",
                ui: true,
            },
            rspeed: {
                buff: true,
                duration: 2700000,
                explanation: "Increases movement speed and attack speed.",
                frequency: 8,
                name: "Rogue Swiftness",
                skin: "buff_speed",
                speed: 7,
                ui: true,
            },
            sanguine: {
                attr0: "lifesteal",
                aura: true,
                buff: true,
                duration: 30000,
                explanation: "Bite back with every hit.",
                name: "Vampiric Aura",
                skin: "sanguine",
                ui: true,
            },
            shocked: {
                debuff: true,
                duration: 1600,
                explanation: "Imminent magical damage.",
                name: "Shocked",
                skin: "essenceofthunder",
                ui: true,
            },
            sleeping: {
                debuff: true,
                duration: 8000,
                duration_min: 3000,
                name: "Sleeping",
            },
            slowness: {
                debuff: true,
                explanation: "Things like spiderwebs cause you to slow down.",
                name: "Slowness",
                skin: "condition_neutral",
                speed: -40,
                ui: true,
            },
            stack: {
                debuff: true,
                explanation: "Bonus damage for each rogue attack.",
                name: "Pure Damage",
                skin: "skill_stack",
            },
            stoned: {
                blocked: true,
                debuff: true,
                duration: 4000,
                explanation: "Cannot move, attack, heal, or use skills.",
                name: "Stoned",
                skin: "condition_neutral",
            },
            stunned: {
                blocked: true,
                debuff: true,
                defense: "phresistance",
                duration: 3200,
                explanation: "Cannot move, attack, heal, or use skills.",
                name: "Stunned",
                skin: "condition_bad",
                ui: true,
            },
            sugarrush: {
                buff: true,
                duration: 10000,
                explanation: "Greatly increases attack speed and reduces mana cost of attacks.",
                frequency: 240,
                mp_cost: -200,
                name: "Sugar Rush",
                skin: "candycanesword",
                ui: true,
            },
            tangled: {
                debuff: true,
                duration: 12000,
                explanation: "Sets maximum speed to 24.",
                name: "Tangled",
                set_speed: 24,
                skin: "condition_bad",
                ui: false,
            },
            town: {
                can_move: true,
                channel: true,
                duration: 3000,
                explanation: "Town in progress.",
                name: "Town",
                skin: "condition_positive",
            },
            warcry: {
                armor: 160,
                buff: true,
                duration: 8000,
                explanation: "Boosts attack speed, movement speed, armor, and resistance.",
                frequency: 10,
                name: "War Cry",
                resistance: 160,
                skin: "skill_warcry",
                speed: 20,
                ui: true,
            },
            weakness: {
                debuff: true,
                dex: -10,
                duration: 20000,
                explanation: "Reduces speed, dexterity, and strength.",
                name: "Weakness",
                skin: "condition_bad",
                speed: -30,
                str: -10,
                ui: true,
            },
            withdrawal: {
                debuff: true,
                dex: -20,
                duration: 10800000,
                explanation: "Reduced stats.",
                frequency: -30,
                mp: -300,
                name: "Withdrawal",
                persistent: true,
                skin: "withdrawal",
                speed: -20,
                str: -5,
                ui: true,
            },
            woven: {
                debuff: true,
                duration: 1000,
                explanation: "Reduces speed by 3 per stack. Stacks up to 20 on monsters, capped at 5 for players.",
                name: "Woven",
                skin: "spidersilk",
                speed: -10,
                ui: true,
            },
            xpower: {
                buff: true,
                duration: 6000,
                explanation: "Greatly increases attack speed and lowers mana cost.",
                frequency: 480,
                mp_cost: -300,
                name: "Power",
                skin: "goldenpowerglove",
                ui: true,
            },
            xshotted: {
                debuff: true,
                duration: 43200000,
                explanation: "Good luck trying to find a tavern to play in.",
                name: "X-Shot",
                persistent: true,
                skin: "xshotted",
                ui: true,
            },
        },
    }
    expect(G_conditions).toBeDefined()
})
