import pkg from "mongoose"
const { Schema } = pkg

const BankSchema = new Schema({
    __v: {
        select: false,
        type: Number
    },
    gold: Number,
    items0: { required: false, type: Object },
    items1: { required: false, type: Object },
    items2: { required: false, type: Object },
    items3: { required: false, type: Object },
    items4: { required: false, type: Object },
    items5: { required: false, type: Object },
    items6: { required: false, type: Object },
    items7: { required: false, type: Object },
    items8: { required: false, type: Object },
    items9: { required: false, type: Object },
    items10: { required: false, type: Object },
    items11: { required: false, type: Object },
    items12: { required: false, type: Object },
    items13: { required: false, type: Object },
    items14: { required: false, type: Object },
    items15: { required: false, type: Object },
    items16: { required: false, type: Object },
    items17: { required: false, type: Object },
    items18: { required: false, type: Object },
    items19: { required: false, type: Object },
    items20: { required: false, type: Object },
    items21: { required: false, type: Object },
    items22: { required: false, type: Object },
    items23: { required: false, type: Object },
    items24: { required: false, type: Object },
    items25: { required: false, type: Object },
    items26: { required: false, type: Object },
    items27: { required: false, type: Object },
    items28: { required: false, type: Object },
    items29: { required: false, type: Object },
    items30: { required: false, type: Object },
    items31: { required: false, type: Object },
    items32: { required: false, type: Object },
    items33: { required: false, type: Object },
    items34: { required: false, type: Object },
    items35: { required: false, type: Object },
    items36: { required: false, type: Object },
    items37: { required: false, type: Object },
    items38: { required: false, type: Object },
    items39: { required: false, type: Object },
    items40: { required: false, type: Object },
    items41: { required: false, type: Object },
    items42: { required: false, type: Object },
    items43: { required: false, type: Object },
    items44: { required: false, type: Object },
    items45: { required: false, type: Object },
    items46: { required: false, type: Object },
    items47: { required: false, type: Object },
    lastUpdated: { required: false, type: Number },
    owner: String
})

export default BankSchema